{{- if .Values.subscriptionURL }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sing-box.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sing-box.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.subscriptionURL | quote }}
{{- end }}
