#!/usr/bin/env python3
"""Generate Codex compatibility skills from Claude Code agents and commands.

Usage:
  cd plugin
  python3 scripts/build_codex_compat_skills.py --repo-root . --out-dir .codex-generated-skills --clean

The generated directories are install artifacts, not source of truth. Source
prompts stay in agents/*.md and commands/*.md.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text

    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            raw = "\n".join(lines[1:index])
            body = "\n".join(lines[index + 1 :]).lstrip("\n")
            return parse_frontmatter(raw), body

    return {}, text


def parse_frontmatter(raw: str) -> dict[str, str]:
    parsed: dict[str, str] = {}
    lines = raw.splitlines()
    index = 0

    while index < len(lines):
        line = lines[index]
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or ":" not in line:
            index += 1
            continue

        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()

        if value in {"|", "|-", "|+", ">", ">-", ">+"}:
            block, index = consume_block(lines, index + 1)
            parsed[key] = block
            continue

        parsed[key] = unquote_scalar(value)
        index += 1

    return parsed


def consume_block(lines: list[str], start: int) -> tuple[str, int]:
    block: list[str] = []
    index = start

    while index < len(lines):
        line = lines[index]
        if line.strip() and not line.startswith((" ", "\t")) and ":" in line:
            break
        block.append(line[2:] if line.startswith("  ") else line.lstrip())
        index += 1

    return "\n".join(block).rstrip(), index


def unquote_scalar(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def skill_name(raw: str, fallback: str) -> str:
    value = raw or fallback
    normalized = re.sub(r"[^A-Za-z0-9]+", "-", value.strip().lower())
    normalized = re.sub(r"-{2,}", "-", normalized).strip("-")
    if not normalized:
        raise ValueError(f"Cannot derive skill name from {raw!r}")
    return normalized


def title_from_name(name: str) -> str:
    return " ".join(part.capitalize() for part in re.split(r"[-_]+", name) if part)


def load_plugin_name(repo_root: Path) -> str:
    for manifest in (
        repo_root / ".claude-plugin" / "plugin.json",
        repo_root / ".codex-plugin" / "plugin.json",
    ):
        if not manifest.is_file():
            continue
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        name = data.get("name")
        if isinstance(name, str) and name.strip():
            return name.strip()
    return repo_root.name


def yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_agent_skill(
    *,
    name: str,
    plugin_name: str,
    source_rel: str,
    metadata: dict[str, str],
    body: str,
) -> str:
    declared_tools = metadata.get("tools", "").strip()
    source_title = title_from_name(name)
    description = (
        f"Use when the user explicitly asks for the converted Claude Code agent `{name}`, "
        "or when a converted command references this named agent. This Codex skill adapts "
        "the original agent prompt without relying on Claude Code's agent registry."
    )

    tools_line = f"- Declared tools: `{declared_tools}`\n" if declared_tools else ""

    return f"""---
name: {name}
description: {yaml_string(description)}
metadata:
  category: compatibility
  generated_from: {yaml_string(source_rel)}
---

<!-- Generated by scripts/build_codex_compat_skills.py from {source_rel}. Do not edit by hand. -->

# {source_title}

This is a Codex compatibility wrapper for the Claude Code agent `{name}` from `{plugin_name}`.

## Codex adaptation

- Treat the original prompt below as role instructions for the active Codex agent.
- Apply the source tool contract using Codex tools. If the source agent is read-only, do not edit files.
- If the prompt references Claude-only mechanisms such as the Agent tool or registered agent types, use available Codex multi-agent tools when they exist. If they are unavailable, execute the role instructions directly and state that limitation.
- Keep the source prompt's output contract unless the user asks for a different format.

## Source metadata

- Type: Claude Code agent
- Source: `{source_rel}`
{tools_line}
## Original instructions

{body.rstrip()}
"""


def render_command_skill(
    *,
    name: str,
    plugin_name: str,
    source_rel: str,
    metadata: dict[str, str],
    body: str,
) -> str:
    source_title = f"/{name}"
    original_description = metadata.get("description", "").strip()
    argument_hint = first_present(metadata, "argument-hint", "argument_hint", "args")
    trigger = original_description or f"Run the converted Claude Code command `{name}`."
    description = (
        f"{as_sentence(trigger)} Use when the user invokes `/{name}` or explicitly asks to run "
        "this converted Claude Code command workflow in Codex."
    )

    original_desc_line = (
        f"- Original description: {original_description}\n" if original_description else ""
    )
    argument_line = f"- Arguments: `{argument_hint}`\n" if argument_hint else ""

    return f"""---
name: {name}
description: {yaml_string(description)}
metadata:
  category: compatibility
  generated_from: {yaml_string(source_rel)}
---

<!-- Generated by scripts/build_codex_compat_skills.py from {source_rel}. Do not edit by hand. -->

# {source_title}

This is a Codex compatibility wrapper for the Claude Code slash command `/{name}` from `{plugin_name}`.

## Codex adaptation

- Interpret command arguments from the user's request. If required arguments are missing, ask one focused question.
- Execute the workflow with Codex shell/tools when the current environment has the required ARL CLI and cluster access. If it does not, explain the missing prerequisite and give the exact command sequence.
- If the original command references Claude Code's Agent tool, use available Codex multi-agent tools when they exist. If they are unavailable, run the referenced converted agent skills as role prompts directly, preferably in the same order and with the same merge/synthesis contract.
- Write files only when the command explicitly requires an output artifact or the user asks for one.
- Keep the source command's output contract unless the user asks for a different format.

## Source metadata

- Type: Claude Code slash command
- Source: `{source_rel}`
{original_desc_line}{argument_line}
## Original instructions

{body.rstrip()}
"""


def first_present(values: dict[str, str], *keys: str) -> str:
    for key in keys:
        value = values.get(key, "").strip()
        if value:
            return value
    return ""


def as_sentence(value: str) -> str:
    stripped = value.strip()
    if not stripped:
        return stripped
    if stripped[-1] in ".!?。！？":
        return stripped
    return f"{stripped}."


def iter_markdown_files(root: Path, dirname: str) -> list[Path]:
    directory = root / dirname
    if not directory.is_dir():
        return []
    return sorted(path for path in directory.glob("*.md") if path.is_file())


def generate_one(repo_root: Path, out_dir: Path, source: Path, kind: str, plugin_name: str) -> str:
    text = source.read_text(encoding="utf-8")
    metadata, body = split_frontmatter(text)
    name = skill_name(metadata.get("name", ""), source.stem)
    source_rel = source.relative_to(repo_root).as_posix()

    if kind == "agent":
        rendered = render_agent_skill(
            name=name,
            plugin_name=plugin_name,
            source_rel=source_rel,
            metadata=metadata,
            body=body,
        )
    elif kind == "command":
        rendered = render_command_skill(
            name=name,
            plugin_name=plugin_name,
            source_rel=source_rel,
            metadata=metadata,
            body=body,
        )
    else:
        raise ValueError(f"Unknown generated skill kind: {kind}")

    skill_dir = out_dir / name
    skill_dir.mkdir(parents=True, exist_ok=False)
    (skill_dir / "SKILL.md").write_text(rendered, encoding="utf-8")
    return name


def clean_output_dir(out_dir: Path, repo_root: Path) -> None:
    resolved_out = out_dir.resolve()
    resolved_repo = repo_root.resolve()
    unsafe_dirs = {
        resolved_repo,
        resolved_repo.parent,
        resolved_repo / "skills",
        resolved_repo / "commands",
        resolved_repo / "agents",
    }
    if resolved_out in unsafe_dirs:
        raise SystemExit(f"Refusing to clean unsafe output directory: {out_dir}")
    if resolved_out.exists():
        shutil.rmtree(resolved_out)
    resolved_out.mkdir(parents=True, exist_ok=True)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--clean", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    repo_root = args.repo_root.expanduser().resolve()
    out_dir = args.out_dir.expanduser().resolve()

    if not repo_root.is_dir():
        raise SystemExit(f"Missing repo root: {repo_root}")
    plugin_name = load_plugin_name(repo_root)

    if args.clean:
        clean_output_dir(out_dir, repo_root)
    else:
        out_dir.mkdir(parents=True, exist_ok=True)

    generated: list[tuple[str, str]] = []
    seen: dict[str, str] = {}

    for kind, dirname in (("agent", "agents"), ("command", "commands")):
        for source in iter_markdown_files(repo_root, dirname):
            metadata, _ = split_frontmatter(source.read_text(encoding="utf-8"))
            name = skill_name(metadata.get("name", ""), source.stem)
            source_rel = source.relative_to(repo_root).as_posix()
            if name in seen:
                raise SystemExit(
                    f"Converted skill name collision: {name} from {source_rel} "
                    f"and {seen[name]}"
                )
            seen[name] = source_rel
            generated_name = generate_one(repo_root, out_dir, source, kind, plugin_name)
            generated.append((kind, generated_name))

    by_kind: dict[str, list[str]] = {"agent": [], "command": []}
    for kind, name in generated:
        by_kind.setdefault(kind, []).append(name)

    print(f"Generated Codex compatibility skills in {out_dir}:")
    print(f"  agents: {', '.join(by_kind.get('agent', [])) or '<none>'}")
    print(f"  commands: {', '.join(by_kind.get('command', [])) or '<none>'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
