FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY iroh-relay /usr/local/bin/iroh-relay
EXPOSE 3340
ENTRYPOINT ["iroh-relay", "--dev"]
