FROM --platform=$BUILDPLATFORM golang:1.26.4-alpine AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace

ENV GOPROXY=https://goproxy.cn,https://goproxy.io,https://proxy.golang.org,direct

COPY go.mod go.sum ./
RUN go mod download

COPY pkg/ pkg/
COPY cmd/gateway/ cmd/gateway/

RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} GOMAXPROCS=8 go build -p 8 -a -o gateway cmd/gateway/main.go

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /workspace/gateway /gateway
ENTRYPOINT ["/gateway"]
CMD ["--port=8080", "--sidecar-grpc-port=9090"]
