apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: arl-infra

# Default build configuration
build:
  artifacts:
  - image: arl-operator
    docker:
      dockerfile: Dockerfile.operator
  - image: arl-sidecar
    docker:
      dockerfile: Dockerfile.sidecar
  - image: arl-gateway
    docker:
      dockerfile: Dockerfile.gateway
  - image: arl-executor-agent
    docker:
      dockerfile: Dockerfile.executor-agent
  tagPolicy:
    gitCommit: {}

# Default manifests - using Helm chart
manifests:
  helm:
    releases:
    - name: arl-operator
      chartPath: charts/arl-operator
      namespace: arl-system
      createNamespace: true
      skipBuildDependencies: true
      setValues:
        crds.install: true
      setValueTemplates:
        image.tag: "{{.IMAGE_TAG}}"
        sidecar.image.tag: "{{.IMAGE_TAG2}}"

# Default deploy configuration (for minikube)
deploy:
  kubectl:
    flags:
      apply:
      - --server-side=true
      - --force-conflicts=true

# Profiles for different environments
profiles:
# Profile for standard Kubernetes with registry
- name: k8s
  build:
    artifacts:
    - image: 10.10.10.240/library/arl-operator
      docker:
        dockerfile: Dockerfile.operator
    - image: 10.10.10.240/library/arl-sidecar
      docker:
        dockerfile: Dockerfile.sidecar
    - image: 10.10.10.240/library/arl-gateway
      docker:
        dockerfile: Dockerfile.gateway
    - image: 10.10.10.240/library/arl-executor-agent
      docker:
        dockerfile: Dockerfile.executor-agent
    tagPolicy:
      sha256: {}
  manifests:
    helm:
      releases:
      - name: arl-operator
        chartPath: charts/arl-operator
        namespace: arl-system
        createNamespace: true
        setValues:
          crds.install: true
          image.repository: 10.10.10.240/library/arl-operator
          sidecar.image.repository: 10.10.10.240/library/arl-sidecar
          gateway.image.repository: 10.10.10.240/library/arl-gateway
          executorAgent.image.repository: 10.10.10.240/library/arl-executor-agent
        setValueTemplates:
          image.tag: "{{.IMAGE_TAG}}"
          sidecar.image.tag: "{{.IMAGE_TAG2}}"
          gateway.image.tag: "{{.IMAGE_TAG3}}"
          executorAgent.image.tag: "{{.IMAGE_TAG4}}"
  deploy:
    kubectl:
      flags:
        apply:
        - --server-side=true
        - --force-conflicts=true
- name: prod
  build:
    artifacts:
    - image: pair-diag-cn-guangzhou.cr.volces.com/pair/arl-operator
      docker:
        dockerfile: Dockerfile.operator
    - image: pair-diag-cn-guangzhou.cr.volces.com/pair/arl-sidecar
      docker:
        dockerfile: Dockerfile.sidecar
    - image: pair-diag-cn-guangzhou.cr.volces.com/pair/arl-gateway
      docker:
        dockerfile: Dockerfile.gateway
    - image: pair-diag-cn-guangzhou.cr.volces.com/pair/arl-executor-agent
      docker:
        dockerfile: Dockerfile.executor-agent
    tagPolicy:
      sha256: {}
  manifests:
    helm:
      releases:
      - name: arl-operator
        chartPath: charts/arl-operator
        namespace: arl
        createNamespace: true
        skipBuildDependencies: true
        setValues:
          crds.install: true
          image.repository: pair-diag-cn-guangzhou.cr.volces.com/pair/arl-operator
          sidecar.image.repository: pair-diag-cn-guangzhou.cr.volces.com/pair/arl-sidecar
          gateway.image.repository: pair-diag-cn-guangzhou.cr.volces.com/pair/arl-gateway
          executorAgent.image.repository: pair-diag-cn-guangzhou.cr.volces.com/pair/arl-executor-agent
          clickhouse.enabled: true
          clickhouse.storageClassName: ebs-ssd
        setValueTemplates:
          image.tag: "{{.IMAGE_TAG}}"
          sidecar.image.tag: "{{.IMAGE_TAG2}}"
          gateway.image.tag: "{{.IMAGE_TAG3}}"
          executorAgent.image.tag: "{{.IMAGE_TAG4}}"
  deploy:
    kubectl:
      flags:
        apply:
        - --server-side=true
        - --force-conflicts=true
# Profile for development with auto-sync and rebuild
- name: dev
  activation:
  - command: dev
  build:
    artifacts:
    - image: arl-operator
      docker:
        dockerfile: Dockerfile.operator
      sync:
        manual:
        - src: 'cmd/**/*.go'
          dest: /app
        - src: 'pkg/**/*.go'
          dest: /app
    - image: arl-sidecar
      docker:
        dockerfile: Dockerfile.sidecar
      sync:
        manual:
        - src: 'cmd/sidecar/**/*.go'
          dest: /app
        - src: 'pkg/sidecar/**/*.go'
          dest: /app
  manifests:
    helm:
      releases:
      - name: arl-operator
        chartPath: charts/arl-operator
        namespace: arl-system
        createNamespace: true
        setValues:
          crds.install: true
        setValueTemplates:
          image.tag: "{{.IMAGE_TAG}}"
          sidecar.image.tag: "{{.IMAGE_TAG2}}"
  deploy:
    kubectl:
      flags:
        apply:
        - --server-side=true
        - --force-conflicts=true

# Profile for deploying samples
- name: with-samples
  manifests:
    helm:
      releases:
      - name: arl-operator
        chartPath: charts/arl-operator
        namespace: arl-system
        createNamespace: true
        setValues:
          crds.install: true
        setValueTemplates:
          image.tag: "{{.IMAGE_TAG}}"
          sidecar.image.tag: "{{.IMAGE_TAG2}}"
    rawYaml:
    - config/samples/*.yaml
  deploy:
    kubectl:
      flags:
        apply:
        - --server-side=true
        - --force-conflicts=true

# Profile for K8s with samples
- name: k8s-with-samples
  build:
    artifacts:
    - image: 10.10.10.240/library/arl-operator
      docker:
        dockerfile: Dockerfile.operator
    - image: 10.10.10.240/library/arl-sidecar
      docker:
        dockerfile: Dockerfile.sidecar
    tagPolicy:
      sha256: {}
  manifests:
    helm:
      releases:
      - name: arl-operator
        chartPath: charts/arl-operator
        namespace: arl-system
        createNamespace: true
        setValues:
          crds.install: true
          image.repository: 10.10.10.240/library/arl-operator
          sidecar.image.repository: 10.10.10.240/library/arl-sidecar
        setValueTemplates:
          image.tag: "{{.IMAGE_TAG}}"
          sidecar.image.tag: "{{.IMAGE_TAG2}}"
    rawYaml:
    - config/samples/*.yaml
  deploy:
    kubectl:
      flags:
        apply:
        - --server-side=true
        - --force-conflicts=true
