---
apiVersion: arl.infra.io/v1alpha1
kind: Task
metadata:
  name: live-test-task
spec:
  sandboxRef: test-sandbox
  timeout: 60s
  steps:
    - name: create_test_script
      type: FilePatch
      path: /workspace/test.py
      content: |
        import datetime
        import platform
        
        print("=" * 60)
        print("LIVE TEST EXECUTION")
        print("=" * 60)
        print(f"Current time: {datetime.datetime.now()}")
        print(f"Python version: {platform.python_version()}")
        print(f"Platform: {platform.platform()}")
        print(f"Machine: {platform.machine()}")
        print("=" * 60)
        print("✓ All tests passed!")
    
    - name: execute_test
      type: Command
      command: ["python", "/workspace/test.py"]
      env:
        TEST_MODE: "live"
    
    - name: verify_workspace
      type: Command
      command: ["ls", "-lh", "/workspace"]
