// This file is @generated by prost-build.
/// Request is the top-level multiplexed client-to-server frame.
/// Each request carries a correlation tag returned verbatim in the
/// matching Response or subsequent Events.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Request {
    #[prost(uint32, tag = "1")]
    pub tag: u32,
    #[prost(
        oneof = "request::Kind",
        tags = "2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15"
    )]
    pub kind: ::core::option::Option<request::Kind>,
}
/// Nested message and enum types in `Request`.
pub mod request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "2")]
        Ping(super::PingRequest),
        #[prost(message, tag = "3")]
        Spawn(super::SpawnRequest),
        #[prost(message, tag = "4")]
        WriteIn(super::WriteInRequest),
        #[prost(message, tag = "5")]
        Signal(super::SignalRequest),
        #[prost(message, tag = "6")]
        Resize(super::ResizeRequest),
        #[prost(message, tag = "7")]
        Read(super::ReadRequest),
        #[prost(message, tag = "8")]
        Write(super::WriteRequest),
        #[prost(message, tag = "9")]
        Stat(super::StatRequest),
        #[prost(message, tag = "10")]
        List(super::ListRequest),
        #[prost(message, tag = "11")]
        Tunnel(super::TunnelRequest),
        #[prost(message, tag = "12")]
        Watch(super::WatchRequest),
        #[prost(message, tag = "13")]
        Unwatch(super::UnwatchRequest),
        #[prost(message, tag = "14")]
        CloseTunnel(super::CloseTunnelRequest),
        #[prost(message, tag = "15")]
        ListTunnels(super::ListTunnelsRequest),
    }
}
/// Response is the top-level server-to-client reply frame.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Response {
    #[prost(uint32, tag = "1")]
    pub tag: u32,
    #[prost(
        oneof = "response::Kind",
        tags = "2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16"
    )]
    pub kind: ::core::option::Option<response::Kind>,
}
/// Nested message and enum types in `Response`.
pub mod response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "2")]
        Ping(super::PingResponse),
        #[prost(message, tag = "3")]
        Spawn(super::SpawnResponse),
        #[prost(message, tag = "4")]
        WriteIn(super::WriteInResponse),
        #[prost(message, tag = "5")]
        Signal(super::SignalResponse),
        #[prost(message, tag = "6")]
        Resize(super::ResizeResponse),
        #[prost(message, tag = "7")]
        Read(super::ReadResponse),
        #[prost(message, tag = "8")]
        Write(super::WriteResponse),
        #[prost(message, tag = "9")]
        Stat(super::StatResponse),
        #[prost(message, tag = "10")]
        List(super::ListResponse),
        #[prost(message, tag = "11")]
        Tunnel(super::TunnelResponse),
        #[prost(message, tag = "12")]
        Watch(super::WatchResponse),
        #[prost(message, tag = "13")]
        Unwatch(super::UnwatchResponse),
        #[prost(message, tag = "14")]
        Error(super::ErrorResponse),
        #[prost(message, tag = "15")]
        CloseTunnel(super::CloseTunnelResponse),
        #[prost(message, tag = "16")]
        ListTunnels(super::ListTunnelsResponse),
    }
}
/// Event is a server-pushed frame for asynchronous notifications.
/// Four event types only; tunnel and file data flow as raw bytes on
/// dedicated streams, not as protobuf Events.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(uint32, tag = "1")]
    pub tag: u32,
    #[prost(oneof = "event::Kind", tags = "2, 3, 4, 5")]
    pub kind: ::core::option::Option<event::Kind>,
}
/// Nested message and enum types in `Event`.
pub mod event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "2")]
        Stdout(super::StdoutEvent),
        #[prost(message, tag = "3")]
        Stderr(super::StderrEvent),
        #[prost(message, tag = "4")]
        Exit(super::ExitEvent),
        #[prost(message, tag = "5")]
        FsChange(super::FsChangeEvent),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PingRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PingResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpawnRequest {
    #[prost(string, repeated, tag = "1")]
    pub command: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "2")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "3")]
    pub working_dir: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub timeout_seconds: i32,
    #[prost(bool, tag = "5")]
    pub pty: bool,
    #[prost(bool, tag = "6")]
    pub stdin: bool,
    #[prost(int32, tag = "7")]
    pub rows: i32,
    #[prost(int32, tag = "8")]
    pub cols: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SpawnResponse {
    #[prost(uint32, tag = "1")]
    pub process_tag: u32,
    #[prost(int32, tag = "2")]
    pub pid: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteInRequest {
    #[prost(uint32, tag = "1")]
    pub process_tag: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WriteInResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalRequest {
    #[prost(uint32, tag = "1")]
    pub process_tag: u32,
    #[prost(string, tag = "2")]
    pub signal: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SignalResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ResizeRequest {
    #[prost(uint32, tag = "1")]
    pub process_tag: u32,
    #[prost(int32, tag = "2")]
    pub rows: i32,
    #[prost(int32, tag = "3")]
    pub cols: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ResizeResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadResponse {
    #[prost(int64, tag = "1")]
    pub size_bytes: i64,
    #[prost(string, tag = "2")]
    pub sha256: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub expected_sha256: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub size_hint: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteResponse {
    #[prost(int64, tag = "1")]
    pub bytes_written: i64,
    #[prost(string, tag = "2")]
    pub sha256: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatResponse {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub size_bytes: i64,
    #[prost(string, tag = "3")]
    pub mode: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub mod_time_unix: i64,
    #[prost(bool, tag = "5")]
    pub is_dir: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub recursive: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListResponse {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<DirEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DirEntry {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub size_bytes: i64,
    #[prost(string, tag = "3")]
    pub mode: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub mod_time_unix: i64,
    #[prost(bool, tag = "5")]
    pub is_dir: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TunnelRequest {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub port: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TunnelResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub recursive: bool,
    #[prost(string, repeated, tag = "3")]
    pub event_types: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WatchResponse {
    #[prost(uint32, tag = "1")]
    pub watch_id: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnwatchRequest {
    #[prost(uint32, tag = "1")]
    pub watch_id: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnwatchResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CloseTunnelRequest {
    #[prost(uint32, tag = "1")]
    pub tunnel_tag: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CloseTunnelResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListTunnelsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTunnelsResponse {
    #[prost(message, repeated, tag = "1")]
    pub tunnels: ::prost::alloc::vec::Vec<TunnelInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TunnelInfo {
    #[prost(uint32, tag = "1")]
    pub tag: u32,
    #[prost(string, tag = "2")]
    pub host: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub port: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StdoutEvent {
    #[prost(uint32, tag = "1")]
    pub process_tag: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StderrEvent {
    #[prost(uint32, tag = "1")]
    pub process_tag: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ExitEvent {
    #[prost(uint32, tag = "1")]
    pub process_tag: u32,
    #[prost(int32, tag = "2")]
    pub exit_code: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FsChangeEvent {
    #[prost(uint32, tag = "1")]
    pub watch_id: u32,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub event_type: ::prost::alloc::string::String,
}
