# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool import WarmPool

class TestWarmPool(unittest.TestCase):
    """WarmPool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPool:
        """Test WarmPool
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPool`
        """
        model = WarmPool()
        if include_optional:
            return WarmPool(
                api_version = 'arl.infra.io/v1alpha1',
                kind = 'WarmPool',
                metadata = arl_client.models.object_meta.ObjectMeta(
                    name = '', 
                    namespace = '', 
                    labels = {
                        'key' : ''
                        }, 
                    annotations = {
                        'key' : ''
                        }, ),
                spec = arl_client.models.warm_pool_spec.WarmPoolSpec(
                    replicas = 56, 
                    template = arl_client.models.pod_template_spec.PodTemplateSpec(
                        metadata = arl_client.models.object_meta.ObjectMeta(
                            name = '', 
                            namespace = '', 
                            labels = {
                                'key' : ''
                                }, 
                            annotations = {
                                'key' : ''
                                }, ), 
                        spec = arl_client.models.spec.spec(), ), ),
                status = arl_client.models.warm_pool_status.WarmPoolStatus(
                    ready_replicas = 56, 
                    allocated_replicas = 56, 
                    conditions = [
                        arl_client.models.condition.Condition(
                            type = '', 
                            status = '', 
                            last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            reason = '', 
                            message = '', )
                        ], )
            )
        else:
            return WarmPool(
        )
        """

    def testWarmPool(self):
        """Test WarmPool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
