# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_sandbox(self) -> None:
        """Test case for create_sandbox

        Create Sandbox
        """
        pass

    def test_create_task(self) -> None:
        """Test case for create_task

        Create Task
        """
        pass

    def test_create_warm_pool(self) -> None:
        """Test case for create_warm_pool

        Create WarmPool
        """
        pass

    def test_list_sandboxes(self) -> None:
        """Test case for list_sandboxes

        List Sandboxes
        """
        pass

    def test_list_tasks(self) -> None:
        """Test case for list_tasks

        List Tasks
        """
        pass

    def test_list_warm_pools(self) -> None:
        """Test case for list_warm_pools

        List WarmPools
        """
        pass


if __name__ == '__main__':
    unittest.main()
