# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle import WarmPoolSpecTemplateSpecContainersInnerLifecycle

class TestWarmPoolSpecTemplateSpecContainersInnerLifecycle(unittest.TestCase):
    """WarmPoolSpecTemplateSpecContainersInnerLifecycle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecContainersInnerLifecycle:
        """Test WarmPoolSpecTemplateSpecContainersInnerLifecycle
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecContainersInnerLifecycle`
        """
        model = WarmPoolSpecTemplateSpecContainersInnerLifecycle()
        if include_optional:
            return WarmPoolSpecTemplateSpecContainersInnerLifecycle(
                post_start = arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle_post_start.WarmPoolSpec_template_spec_containers_inner_lifecycle_postStart(
                    exec = arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle_post_start_exec.WarmPoolSpec_template_spec_containers_inner_lifecycle_postStart_exec(
                        command = [
                            ''
                            ], ), 
                    http_get = arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle_post_start_http_get.WarmPoolSpec_template_spec_containers_inner_lifecycle_postStart_httpGet(
                        host = '', 
                        http_headers = [
                            arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle_post_start_http_get_http_headers_inner.WarmPoolSpec_template_spec_containers_inner_lifecycle_postStart_httpGet_httpHeaders_inner(
                                name = '', 
                                value = '', )
                            ], 
                        path = '', 
                        port = null, 
                        scheme = '', ), 
                    sleep = arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle_post_start_sleep.WarmPoolSpec_template_spec_containers_inner_lifecycle_postStart_sleep(
                        seconds = 56, ), 
                    tcp_socket = arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle_post_start_tcp_socket.WarmPoolSpec_template_spec_containers_inner_lifecycle_postStart_tcpSocket(
                        host = '', 
                        port = null, ), ),
                pre_stop = arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle_post_start.WarmPoolSpec_template_spec_containers_inner_lifecycle_postStart(
                    exec = arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle_post_start_exec.WarmPoolSpec_template_spec_containers_inner_lifecycle_postStart_exec(
                        command = [
                            ''
                            ], ), 
                    http_get = arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle_post_start_http_get.WarmPoolSpec_template_spec_containers_inner_lifecycle_postStart_httpGet(
                        host = '', 
                        http_headers = [
                            arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle_post_start_http_get_http_headers_inner.WarmPoolSpec_template_spec_containers_inner_lifecycle_postStart_httpGet_httpHeaders_inner(
                                name = '', 
                                value = '', )
                            ], 
                        path = '', 
                        port = null, 
                        scheme = '', ), 
                    sleep = arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle_post_start_sleep.WarmPoolSpec_template_spec_containers_inner_lifecycle_postStart_sleep(
                        seconds = 56, ), 
                    tcp_socket = arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle_post_start_tcp_socket.WarmPoolSpec_template_spec_containers_inner_lifecycle_postStart_tcpSocket(
                        host = '', 
                        port = null, ), ),
                stop_signal = ''
            )
        else:
            return WarmPoolSpecTemplateSpecContainersInnerLifecycle(
        )
        """

    def testWarmPoolSpecTemplateSpecContainersInnerLifecycle(self):
        """Test WarmPoolSpecTemplateSpecContainersInnerLifecycle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
