# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.task import Task

class TestTask(unittest.TestCase):
    """Task unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Task:
        """Test Task
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Task`
        """
        model = Task()
        if include_optional:
            return Task(
                api_version = 'arl.infra.io/v1alpha1',
                kind = 'Task',
                metadata = arl_client.models.object_meta.ObjectMeta(
                    name = '', 
                    namespace = '', 
                    labels = {
                        'key' : ''
                        }, 
                    annotations = {
                        'key' : ''
                        }, ),
                spec = arl_client.models.task_spec.TaskSpec(
                    sandbox_ref = '', 
                    timeout = '', 
                    steps = [
                        arl_client.models.task_step.TaskStep(
                            name = '', 
                            type = 'FilePatch', 
                            content = '', 
                            path = '', 
                            command = [
                                ''
                                ], 
                            work_dir = '', 
                            env = {
                                'key' : ''
                                }, )
                        ], 
                    retries = 0, 
                    ttl_seconds_after_finished = 0, ),
                status = arl_client.models.task_status.TaskStatus(
                    state = 'Pending', 
                    exit_code = 56, 
                    stdout = '', 
                    stderr = '', 
                    duration = '', 
                    start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    completion_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    conditions = [
                        arl_client.models.condition.Condition(
                            type = '', 
                            status = '', 
                            last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            reason = '', 
                            message = '', )
                        ], )
            )
        else:
            return Task(
        )
        """

    def testTask(self):
        """Test Task"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
