# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.task_spec import TaskSpec

class TestTaskSpec(unittest.TestCase):
    """TaskSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskSpec:
        """Test TaskSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskSpec`
        """
        model = TaskSpec()
        if include_optional:
            return TaskSpec(
                retries = 0,
                sandbox_ref = '',
                steps = [
                    arl_client.models.task_step.TaskStep(
                        command = ["python","script.py","--verbose"], 
                        content = 'print('Hello, World!')', 
                        env = {"DEBUG":"1","API_KEY":"secret"}, 
                        name = 'step1_write_file', 
                        path = '/workspace/script.py', 
                        type = 'Command', 
                        work_dir = '/workspace', )
                    ],
                timeout = '',
                ttl_seconds_after_finished = 0
            )
        else:
            return TaskSpec(
                sandbox_ref = '',
                steps = [
                    arl_client.models.task_step.TaskStep(
                        command = ["python","script.py","--verbose"], 
                        content = 'print('Hello, World!')', 
                        env = {"DEBUG":"1","API_KEY":"secret"}, 
                        name = 'step1_write_file', 
                        path = '/workspace/script.py', 
                        type = 'Command', 
                        work_dir = '/workspace', )
                    ],
        )
        """

    def testTaskSpec(self):
        """Test TaskSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
