# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.sandbox_spec import SandboxSpec

class TestSandboxSpec(unittest.TestCase):
    """SandboxSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SandboxSpec:
        """Test SandboxSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SandboxSpec`
        """
        model = SandboxSpec()
        if include_optional:
            return SandboxSpec(
                pool_ref = '',
                keep_alive = True,
                resources = arl_client.models.resource_requirements.ResourceRequirements(
                    limits = {
                        'key' : ''
                        }, 
                    requests = {
                        'key' : ''
                        }, )
            )
        else:
            return SandboxSpec(
                pool_ref = '',
        )
        """

    def testSandboxSpec(self):
        """Test SandboxSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
