# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_containers_inner_restart_policy_rules_inner import WarmPoolSpecTemplateSpecContainersInnerRestartPolicyRulesInner

class TestWarmPoolSpecTemplateSpecContainersInnerRestartPolicyRulesInner(unittest.TestCase):
    """WarmPoolSpecTemplateSpecContainersInnerRestartPolicyRulesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecContainersInnerRestartPolicyRulesInner:
        """Test WarmPoolSpecTemplateSpecContainersInnerRestartPolicyRulesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecContainersInnerRestartPolicyRulesInner`
        """
        model = WarmPoolSpecTemplateSpecContainersInnerRestartPolicyRulesInner()
        if include_optional:
            return WarmPoolSpecTemplateSpecContainersInnerRestartPolicyRulesInner(
                action = '',
                exit_codes = arl_client.models.warm_pool_spec_template_spec_containers_inner_restart_policy_rules_inner_exit_codes.WarmPoolSpec_template_spec_containers_inner_restartPolicyRules_inner_exitCodes(
                    operator = '', 
                    values = [
                        56
                        ], )
            )
        else:
            return WarmPoolSpecTemplateSpecContainersInnerRestartPolicyRulesInner(
                action = '',
        )
        """

    def testWarmPoolSpecTemplateSpecContainersInnerRestartPolicyRulesInner(self):
        """Test WarmPoolSpecTemplateSpecContainersInnerRestartPolicyRulesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
