# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_volumes_inner_ephemeral_volume_claim_template_spec_data_source import WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpecDataSource

class TestWarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpecDataSource(unittest.TestCase):
    """WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpecDataSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpecDataSource:
        """Test WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpecDataSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpecDataSource`
        """
        model = WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpecDataSource()
        if include_optional:
            return WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpecDataSource(
                api_group = '',
                kind = '',
                name = ''
            )
        else:
            return WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpecDataSource(
                kind = '',
                name = '',
        )
        """

    def testWarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpecDataSource(self):
        """Test WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpecDataSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
