# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_volumes_inner import WarmPoolSpecTemplateSpecVolumesInner

class TestWarmPoolSpecTemplateSpecVolumesInner(unittest.TestCase):
    """WarmPoolSpecTemplateSpecVolumesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecVolumesInner:
        """Test WarmPoolSpecTemplateSpecVolumesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecVolumesInner`
        """
        model = WarmPoolSpecTemplateSpecVolumesInner()
        if include_optional:
            return WarmPoolSpecTemplateSpecVolumesInner(
                aws_elastic_block_store = arl_client.models.warm_pool_spec_template_spec_volumes_inner_aws_elastic_block_store.WarmPoolSpec_template_spec_volumes_inner_awsElasticBlockStore(
                    fs_type = '', 
                    partition = 56, 
                    read_only = True, 
                    volume_id = '', ),
                azure_disk = arl_client.models.warm_pool_spec_template_spec_volumes_inner_azure_disk.WarmPoolSpec_template_spec_volumes_inner_azureDisk(
                    caching_mode = '', 
                    disk_name = '', 
                    disk_uri = '', 
                    fs_type = 'ext4', 
                    kind = '', 
                    read_only = True, ),
                azure_file = arl_client.models.warm_pool_spec_template_spec_volumes_inner_azure_file.WarmPoolSpec_template_spec_volumes_inner_azureFile(
                    read_only = True, 
                    secret_name = '', 
                    share_name = '', ),
                cephfs = arl_client.models.warm_pool_spec_template_spec_volumes_inner_cephfs.WarmPoolSpec_template_spec_volumes_inner_cephfs(
                    monitors = [
                        ''
                        ], 
                    path = '', 
                    read_only = True, 
                    secret_file = '', 
                    secret_ref = arl_client.models.warm_pool_spec_template_spec_image_pull_secrets_inner.WarmPoolSpec_template_spec_imagePullSecrets_inner(
                        name = '', ), 
                    user = '', ),
                cinder = arl_client.models.warm_pool_spec_template_spec_volumes_inner_cinder.WarmPoolSpec_template_spec_volumes_inner_cinder(
                    fs_type = '', 
                    read_only = True, 
                    secret_ref = arl_client.models.warm_pool_spec_template_spec_image_pull_secrets_inner.WarmPoolSpec_template_spec_imagePullSecrets_inner(
                        name = '', ), 
                    volume_id = '', ),
                config_map = arl_client.models.warm_pool_spec_template_spec_volumes_inner_config_map.WarmPoolSpec_template_spec_volumes_inner_configMap(
                    default_mode = 56, 
                    items = [
                        arl_client.models.warm_pool_spec_template_spec_volumes_inner_config_map_items_inner.WarmPoolSpec_template_spec_volumes_inner_configMap_items_inner(
                            key = '', 
                            mode = 56, 
                            path = '', )
                        ], 
                    name = '', 
                    optional = True, ),
                csi = arl_client.models.warm_pool_spec_template_spec_volumes_inner_csi.WarmPoolSpec_template_spec_volumes_inner_csi(
                    driver = '', 
                    fs_type = '', 
                    node_publish_secret_ref = arl_client.models.warm_pool_spec_template_spec_image_pull_secrets_inner.WarmPoolSpec_template_spec_imagePullSecrets_inner(
                        name = '', ), 
                    read_only = True, 
                    volume_attributes = {
                        'key' : ''
                        }, ),
                downward_api = arl_client.models.warm_pool_spec_template_spec_volumes_inner_downward_api.WarmPoolSpec_template_spec_volumes_inner_downwardAPI(
                    default_mode = 56, 
                    items = [
                        arl_client.models.warm_pool_spec_template_spec_volumes_inner_downward_api_items_inner.WarmPoolSpec_template_spec_volumes_inner_downwardAPI_items_inner(
                            field_ref = arl_client.models.warm_pool_spec_template_spec_containers_inner_env_inner_value_from_field_ref.WarmPoolSpec_template_spec_containers_inner_env_inner_valueFrom_fieldRef(
                                api_version = '', 
                                field_path = '', ), 
                            mode = 56, 
                            path = '', 
                            resource_field_ref = arl_client.models.warm_pool_spec_template_spec_containers_inner_env_inner_value_from_resource_field_ref.WarmPoolSpec_template_spec_containers_inner_env_inner_valueFrom_resourceFieldRef(
                                container_name = '', 
                                divisor = null, 
                                resource = '', ), )
                        ], ),
                empty_dir = arl_client.models.warm_pool_spec_template_spec_volumes_inner_empty_dir.WarmPoolSpec_template_spec_volumes_inner_emptyDir(
                    medium = '', 
                    size_limit = null, ),
                ephemeral = arl_client.models.warm_pool_spec_template_spec_volumes_inner_ephemeral.WarmPoolSpec_template_spec_volumes_inner_ephemeral(
                    volume_claim_template = arl_client.models.warm_pool_spec_template_spec_volumes_inner_ephemeral_volume_claim_template.WarmPoolSpec_template_spec_volumes_inner_ephemeral_volumeClaimTemplate(
                        metadata = arl_client.models.metadata.metadata(), 
                        spec = arl_client.models.warm_pool_spec_template_spec_volumes_inner_ephemeral_volume_claim_template_spec.WarmPoolSpec_template_spec_volumes_inner_ephemeral_volumeClaimTemplate_spec(
                            access_modes = [
                                ''
                                ], 
                            data_source = arl_client.models.warm_pool_spec_template_spec_volumes_inner_ephemeral_volume_claim_template_spec_data_source.WarmPoolSpec_template_spec_volumes_inner_ephemeral_volumeClaimTemplate_spec_dataSource(
                                api_group = '', 
                                kind = '', 
                                name = '', ), 
                            data_source_ref = arl_client.models.warm_pool_spec_template_spec_volumes_inner_ephemeral_volume_claim_template_spec_data_source_ref.WarmPoolSpec_template_spec_volumes_inner_ephemeral_volumeClaimTemplate_spec_dataSourceRef(
                                api_group = '', 
                                kind = '', 
                                name = '', 
                                namespace = '', ), 
                            resources = arl_client.models.warm_pool_spec_template_spec_volumes_inner_ephemeral_volume_claim_template_spec_resources.WarmPoolSpec_template_spec_volumes_inner_ephemeral_volumeClaimTemplate_spec_resources(
                                limits = {
                                    'key' : null
                                    }, 
                                requests = {
                                    'key' : null
                                    }, ), 
                            selector = arl_client.models.warm_pool_spec_template_spec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector.WarmPoolSpec_template_spec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector(
                                match_expressions = [
                                    arl_client.models.warm_pool_spec_template_spec_affinity_node_affinity_preferred_during_scheduling_ignored_during_execution_inner_preference_match_expressions_inner.WarmPoolSpec_template_spec_affinity_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_preference_matchExpressions_inner(
                                        key = '', 
                                        operator = '', 
                                        values = [
                                            ''
                                            ], )
                                    ], 
                                match_labels = {
                                    'key' : ''
                                    }, ), 
                            storage_class_name = '', 
                            volume_attributes_class_name = '', 
                            volume_mode = '', 
                            volume_name = '', ), ), ),
                fc = arl_client.models.warm_pool_spec_template_spec_volumes_inner_fc.WarmPoolSpec_template_spec_volumes_inner_fc(
                    fs_type = '', 
                    lun = 56, 
                    read_only = True, 
                    target_wwns = [
                        ''
                        ], 
                    wwids = [
                        ''
                        ], ),
                flex_volume = arl_client.models.warm_pool_spec_template_spec_volumes_inner_flex_volume.WarmPoolSpec_template_spec_volumes_inner_flexVolume(
                    driver = '', 
                    fs_type = '', 
                    options = {
                        'key' : ''
                        }, 
                    read_only = True, 
                    secret_ref = arl_client.models.warm_pool_spec_template_spec_image_pull_secrets_inner.WarmPoolSpec_template_spec_imagePullSecrets_inner(
                        name = '', ), ),
                flocker = arl_client.models.warm_pool_spec_template_spec_volumes_inner_flocker.WarmPoolSpec_template_spec_volumes_inner_flocker(
                    dataset_name = '', 
                    dataset_uuid = '', ),
                gce_persistent_disk = arl_client.models.warm_pool_spec_template_spec_volumes_inner_gce_persistent_disk.WarmPoolSpec_template_spec_volumes_inner_gcePersistentDisk(
                    fs_type = '', 
                    partition = 56, 
                    pd_name = '', 
                    read_only = True, ),
                git_repo = arl_client.models.warm_pool_spec_template_spec_volumes_inner_git_repo.WarmPoolSpec_template_spec_volumes_inner_gitRepo(
                    directory = '', 
                    repository = '', 
                    revision = '', ),
                glusterfs = arl_client.models.warm_pool_spec_template_spec_volumes_inner_glusterfs.WarmPoolSpec_template_spec_volumes_inner_glusterfs(
                    endpoints = '', 
                    path = '', 
                    read_only = True, ),
                host_path = arl_client.models.warm_pool_spec_template_spec_volumes_inner_host_path.WarmPoolSpec_template_spec_volumes_inner_hostPath(
                    path = '', 
                    type = '', ),
                image = arl_client.models.warm_pool_spec_template_spec_volumes_inner_image.WarmPoolSpec_template_spec_volumes_inner_image(
                    pull_policy = '', 
                    reference = '', ),
                iscsi = arl_client.models.warm_pool_spec_template_spec_volumes_inner_iscsi.WarmPoolSpec_template_spec_volumes_inner_iscsi(
                    chap_auth_discovery = True, 
                    chap_auth_session = True, 
                    fs_type = '', 
                    initiator_name = '', 
                    iqn = '', 
                    iscsi_interface = 'default', 
                    lun = 56, 
                    portals = [
                        ''
                        ], 
                    read_only = True, 
                    secret_ref = arl_client.models.warm_pool_spec_template_spec_image_pull_secrets_inner.WarmPoolSpec_template_spec_imagePullSecrets_inner(
                        name = '', ), 
                    target_portal = '', ),
                name = '',
                nfs = arl_client.models.warm_pool_spec_template_spec_volumes_inner_nfs.WarmPoolSpec_template_spec_volumes_inner_nfs(
                    path = '', 
                    read_only = True, 
                    server = '', ),
                persistent_volume_claim = arl_client.models.warm_pool_spec_template_spec_volumes_inner_persistent_volume_claim.WarmPoolSpec_template_spec_volumes_inner_persistentVolumeClaim(
                    claim_name = '', 
                    read_only = True, ),
                photon_persistent_disk = arl_client.models.warm_pool_spec_template_spec_volumes_inner_photon_persistent_disk.WarmPoolSpec_template_spec_volumes_inner_photonPersistentDisk(
                    fs_type = '', 
                    pd_id = '', ),
                portworx_volume = arl_client.models.warm_pool_spec_template_spec_volumes_inner_portworx_volume.WarmPoolSpec_template_spec_volumes_inner_portworxVolume(
                    fs_type = '', 
                    read_only = True, 
                    volume_id = '', ),
                projected = arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected.WarmPoolSpec_template_spec_volumes_inner_projected(
                    default_mode = 56, 
                    sources = [
                        arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner.WarmPoolSpec_template_spec_volumes_inner_projected_sources_inner(
                            cluster_trust_bundle = arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner_cluster_trust_bundle.WarmPoolSpec_template_spec_volumes_inner_projected_sources_inner_clusterTrustBundle(
                                label_selector = arl_client.models.warm_pool_spec_template_spec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector.WarmPoolSpec_template_spec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector(
                                    match_expressions = [
                                        arl_client.models.warm_pool_spec_template_spec_affinity_node_affinity_preferred_during_scheduling_ignored_during_execution_inner_preference_match_expressions_inner.WarmPoolSpec_template_spec_affinity_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_preference_matchExpressions_inner(
                                            key = '', 
                                            operator = '', 
                                            values = [
                                                ''
                                                ], )
                                        ], 
                                    match_labels = {
                                        'key' : ''
                                        }, ), 
                                name = '', 
                                optional = True, 
                                path = '', 
                                signer_name = '', ), 
                            config_map = arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner_config_map.WarmPoolSpec_template_spec_volumes_inner_projected_sources_inner_configMap(
                                items = [
                                    arl_client.models.warm_pool_spec_template_spec_volumes_inner_config_map_items_inner.WarmPoolSpec_template_spec_volumes_inner_configMap_items_inner(
                                        key = '', 
                                        mode = 56, 
                                        path = '', )
                                    ], 
                                name = '', 
                                optional = True, ), 
                            downward_api = arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner_downward_api.WarmPoolSpec_template_spec_volumes_inner_projected_sources_inner_downwardAPI(), 
                            pod_certificate = arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner_pod_certificate.WarmPoolSpec_template_spec_volumes_inner_projected_sources_inner_podCertificate(
                                certificate_chain_path = '', 
                                credential_bundle_path = '', 
                                key_path = '', 
                                key_type = '', 
                                max_expiration_seconds = 56, 
                                signer_name = '', 
                                user_annotations = {
                                    'key' : ''
                                    }, ), 
                            secret = arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner_config_map.WarmPoolSpec_template_spec_volumes_inner_projected_sources_inner_configMap(
                                name = '', 
                                optional = True, ), 
                            service_account_token = arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner_service_account_token.WarmPoolSpec_template_spec_volumes_inner_projected_sources_inner_serviceAccountToken(
                                audience = '', 
                                expiration_seconds = 56, 
                                path = '', ), )
                        ], ),
                quobyte = arl_client.models.warm_pool_spec_template_spec_volumes_inner_quobyte.WarmPoolSpec_template_spec_volumes_inner_quobyte(
                    group = '', 
                    read_only = True, 
                    registry = '', 
                    tenant = '', 
                    user = '', 
                    volume = '', ),
                rbd = arl_client.models.warm_pool_spec_template_spec_volumes_inner_rbd.WarmPoolSpec_template_spec_volumes_inner_rbd(
                    fs_type = '', 
                    image = '', 
                    keyring = '/etc/ceph/keyring', 
                    monitors = [
                        ''
                        ], 
                    pool = 'rbd', 
                    read_only = True, 
                    secret_ref = arl_client.models.warm_pool_spec_template_spec_image_pull_secrets_inner.WarmPoolSpec_template_spec_imagePullSecrets_inner(
                        name = '', ), 
                    user = 'admin', ),
                scale_io = arl_client.models.warm_pool_spec_template_spec_volumes_inner_scale_io.WarmPoolSpec_template_spec_volumes_inner_scaleIO(
                    fs_type = 'xfs', 
                    gateway = '', 
                    protection_domain = '', 
                    read_only = True, 
                    secret_ref = arl_client.models.warm_pool_spec_template_spec_image_pull_secrets_inner.WarmPoolSpec_template_spec_imagePullSecrets_inner(
                        name = '', ), 
                    ssl_enabled = True, 
                    storage_mode = 'ThinProvisioned', 
                    storage_pool = '', 
                    system = '', 
                    volume_name = '', ),
                secret = arl_client.models.warm_pool_spec_template_spec_volumes_inner_secret.WarmPoolSpec_template_spec_volumes_inner_secret(
                    default_mode = 56, 
                    items = [
                        arl_client.models.warm_pool_spec_template_spec_volumes_inner_config_map_items_inner.WarmPoolSpec_template_spec_volumes_inner_configMap_items_inner(
                            key = '', 
                            mode = 56, 
                            path = '', )
                        ], 
                    optional = True, 
                    secret_name = '', ),
                storageos = arl_client.models.warm_pool_spec_template_spec_volumes_inner_storageos.WarmPoolSpec_template_spec_volumes_inner_storageos(
                    fs_type = '', 
                    read_only = True, 
                    secret_ref = arl_client.models.warm_pool_spec_template_spec_image_pull_secrets_inner.WarmPoolSpec_template_spec_imagePullSecrets_inner(
                        name = '', ), 
                    volume_name = '', 
                    volume_namespace = '', ),
                vsphere_volume = arl_client.models.warm_pool_spec_template_spec_volumes_inner_vsphere_volume.WarmPoolSpec_template_spec_volumes_inner_vsphereVolume(
                    fs_type = '', 
                    storage_policy_id = '', 
                    storage_policy_name = '', 
                    volume_path = '', )
            )
        else:
            return WarmPoolSpecTemplateSpecVolumesInner(
                name = '',
        )
        """

    def testWarmPoolSpecTemplateSpecVolumesInner(self):
        """Test WarmPoolSpecTemplateSpecVolumesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
