# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_security_context import WarmPoolSpecTemplateSpecSecurityContext

class TestWarmPoolSpecTemplateSpecSecurityContext(unittest.TestCase):
    """WarmPoolSpecTemplateSpecSecurityContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecSecurityContext:
        """Test WarmPoolSpecTemplateSpecSecurityContext
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecSecurityContext`
        """
        model = WarmPoolSpecTemplateSpecSecurityContext()
        if include_optional:
            return WarmPoolSpecTemplateSpecSecurityContext(
                app_armor_profile = arl_client.models.warm_pool_spec_template_spec_containers_inner_security_context_app_armor_profile.WarmPoolSpec_template_spec_containers_inner_securityContext_appArmorProfile(
                    localhost_profile = '', 
                    type = '', ),
                fs_group = 56,
                fs_group_change_policy = '',
                run_as_group = 56,
                run_as_non_root = True,
                run_as_user = 56,
                se_linux_change_policy = '',
                se_linux_options = arl_client.models.warm_pool_spec_template_spec_containers_inner_security_context_se_linux_options.WarmPoolSpec_template_spec_containers_inner_securityContext_seLinuxOptions(
                    level = '', 
                    role = '', 
                    type = '', 
                    user = '', ),
                seccomp_profile = arl_client.models.warm_pool_spec_template_spec_containers_inner_security_context_app_armor_profile.WarmPoolSpec_template_spec_containers_inner_securityContext_appArmorProfile(
                    localhost_profile = '', 
                    type = '', ),
                supplemental_groups = [
                    56
                    ],
                supplemental_groups_policy = '',
                sysctls = [
                    arl_client.models.warm_pool_spec_template_spec_containers_inner_lifecycle_post_start_http_get_http_headers_inner.WarmPoolSpec_template_spec_containers_inner_lifecycle_postStart_httpGet_httpHeaders_inner(
                        name = '', 
                        value = '', )
                    ],
                windows_options = arl_client.models.warm_pool_spec_template_spec_containers_inner_security_context_windows_options.WarmPoolSpec_template_spec_containers_inner_securityContext_windowsOptions(
                    gmsa_credential_spec = '', 
                    gmsa_credential_spec_name = '', 
                    host_process = True, 
                    run_as_user_name = '', )
            )
        else:
            return WarmPoolSpecTemplateSpecSecurityContext(
        )
        """

    def testWarmPoolSpecTemplateSpecSecurityContext(self):
        """Test WarmPoolSpecTemplateSpecSecurityContext"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
