# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_volumes_inner_rbd import WarmPoolSpecTemplateSpecVolumesInnerRbd

class TestWarmPoolSpecTemplateSpecVolumesInnerRbd(unittest.TestCase):
    """WarmPoolSpecTemplateSpecVolumesInnerRbd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecVolumesInnerRbd:
        """Test WarmPoolSpecTemplateSpecVolumesInnerRbd
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecVolumesInnerRbd`
        """
        model = WarmPoolSpecTemplateSpecVolumesInnerRbd()
        if include_optional:
            return WarmPoolSpecTemplateSpecVolumesInnerRbd(
                fs_type = '',
                image = '',
                keyring = '/etc/ceph/keyring',
                monitors = [
                    ''
                    ],
                pool = 'rbd',
                read_only = True,
                secret_ref = arl_client.models.warm_pool_spec_template_spec_image_pull_secrets_inner.WarmPoolSpec_template_spec_imagePullSecrets_inner(
                    name = '', ),
                user = 'admin'
            )
        else:
            return WarmPoolSpecTemplateSpecVolumesInnerRbd(
                image = '',
                monitors = [
                    ''
                    ],
        )
        """

    def testWarmPoolSpecTemplateSpecVolumesInnerRbd(self):
        """Test WarmPoolSpecTemplateSpecVolumesInnerRbd"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
