# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_containers_inner_env_inner_value_from import WarmPoolSpecTemplateSpecContainersInnerEnvInnerValueFrom

class TestWarmPoolSpecTemplateSpecContainersInnerEnvInnerValueFrom(unittest.TestCase):
    """WarmPoolSpecTemplateSpecContainersInnerEnvInnerValueFrom unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecContainersInnerEnvInnerValueFrom:
        """Test WarmPoolSpecTemplateSpecContainersInnerEnvInnerValueFrom
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecContainersInnerEnvInnerValueFrom`
        """
        model = WarmPoolSpecTemplateSpecContainersInnerEnvInnerValueFrom()
        if include_optional:
            return WarmPoolSpecTemplateSpecContainersInnerEnvInnerValueFrom(
                config_map_key_ref = arl_client.models.warm_pool_spec_template_spec_containers_inner_env_inner_value_from_config_map_key_ref.WarmPoolSpec_template_spec_containers_inner_env_inner_valueFrom_configMapKeyRef(
                    key = '', 
                    name = '', 
                    optional = True, ),
                field_ref = arl_client.models.warm_pool_spec_template_spec_containers_inner_env_inner_value_from_field_ref.WarmPoolSpec_template_spec_containers_inner_env_inner_valueFrom_fieldRef(
                    api_version = '', 
                    field_path = '', ),
                file_key_ref = arl_client.models.warm_pool_spec_template_spec_containers_inner_env_inner_value_from_file_key_ref.WarmPoolSpec_template_spec_containers_inner_env_inner_valueFrom_fileKeyRef(
                    key = '', 
                    optional = True, 
                    path = '', 
                    volume_name = '', ),
                resource_field_ref = arl_client.models.warm_pool_spec_template_spec_containers_inner_env_inner_value_from_resource_field_ref.WarmPoolSpec_template_spec_containers_inner_env_inner_valueFrom_resourceFieldRef(
                    container_name = '', 
                    divisor = null, 
                    resource = '', ),
                secret_key_ref = arl_client.models.warm_pool_spec_template_spec_containers_inner_env_inner_value_from_config_map_key_ref.WarmPoolSpec_template_spec_containers_inner_env_inner_valueFrom_configMapKeyRef(
                    key = '', 
                    name = '', 
                    optional = True, )
            )
        else:
            return WarmPoolSpecTemplateSpecContainersInnerEnvInnerValueFrom(
        )
        """

    def testWarmPoolSpecTemplateSpecContainersInnerEnvInnerValueFrom(self):
        """Test WarmPoolSpecTemplateSpecContainersInnerEnvInnerValueFrom"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
