# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_volumes_inner_ephemeral_volume_claim_template_spec import WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec

class TestWarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec(unittest.TestCase):
    """WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec:
        """Test WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec`
        """
        model = WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec()
        if include_optional:
            return WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec(
                access_modes = [
                    ''
                    ],
                data_source = arl_client.models.warm_pool_spec_template_spec_volumes_inner_ephemeral_volume_claim_template_spec_data_source.WarmPoolSpec_template_spec_volumes_inner_ephemeral_volumeClaimTemplate_spec_dataSource(
                    api_group = '', 
                    kind = '', 
                    name = '', ),
                data_source_ref = arl_client.models.warm_pool_spec_template_spec_volumes_inner_ephemeral_volume_claim_template_spec_data_source_ref.WarmPoolSpec_template_spec_volumes_inner_ephemeral_volumeClaimTemplate_spec_dataSourceRef(
                    api_group = '', 
                    kind = '', 
                    name = '', 
                    namespace = '', ),
                resources = arl_client.models.warm_pool_spec_template_spec_volumes_inner_ephemeral_volume_claim_template_spec_resources.WarmPoolSpec_template_spec_volumes_inner_ephemeral_volumeClaimTemplate_spec_resources(
                    limits = {
                        'key' : null
                        }, 
                    requests = {
                        'key' : null
                        }, ),
                selector = arl_client.models.warm_pool_spec_template_spec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector.WarmPoolSpec_template_spec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector(
                    match_expressions = [
                        arl_client.models.warm_pool_spec_template_spec_affinity_node_affinity_preferred_during_scheduling_ignored_during_execution_inner_preference_match_expressions_inner.WarmPoolSpec_template_spec_affinity_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_preference_matchExpressions_inner(
                            key = '', 
                            operator = '', 
                            values = [
                                ''
                                ], )
                        ], 
                    match_labels = {
                        'key' : ''
                        }, ),
                storage_class_name = '',
                volume_attributes_class_name = '',
                volume_mode = '',
                volume_name = ''
            )
        else:
            return WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec(
        )
        """

    def testWarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec(self):
        """Test WarmPoolSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
