# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_volumes_inner_downward_api import WarmPoolSpecTemplateSpecVolumesInnerDownwardAPI

class TestWarmPoolSpecTemplateSpecVolumesInnerDownwardAPI(unittest.TestCase):
    """WarmPoolSpecTemplateSpecVolumesInnerDownwardAPI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecVolumesInnerDownwardAPI:
        """Test WarmPoolSpecTemplateSpecVolumesInnerDownwardAPI
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecVolumesInnerDownwardAPI`
        """
        model = WarmPoolSpecTemplateSpecVolumesInnerDownwardAPI()
        if include_optional:
            return WarmPoolSpecTemplateSpecVolumesInnerDownwardAPI(
                default_mode = 56,
                items = [
                    arl_client.models.warm_pool_spec_template_spec_volumes_inner_downward_api_items_inner.WarmPoolSpec_template_spec_volumes_inner_downwardAPI_items_inner(
                        field_ref = arl_client.models.warm_pool_spec_template_spec_containers_inner_env_inner_value_from_field_ref.WarmPoolSpec_template_spec_containers_inner_env_inner_valueFrom_fieldRef(
                            api_version = '', 
                            field_path = '', ), 
                        mode = 56, 
                        path = '', 
                        resource_field_ref = arl_client.models.warm_pool_spec_template_spec_containers_inner_env_inner_value_from_resource_field_ref.WarmPoolSpec_template_spec_containers_inner_env_inner_valueFrom_resourceFieldRef(
                            container_name = '', 
                            divisor = null, 
                            resource = '', ), )
                    ]
            )
        else:
            return WarmPoolSpecTemplateSpecVolumesInnerDownwardAPI(
        )
        """

    def testWarmPoolSpecTemplateSpecVolumesInnerDownwardAPI(self):
        """Test WarmPoolSpecTemplateSpecVolumesInnerDownwardAPI"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
