# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_volumes_inner_csi import WarmPoolSpecTemplateSpecVolumesInnerCsi

class TestWarmPoolSpecTemplateSpecVolumesInnerCsi(unittest.TestCase):
    """WarmPoolSpecTemplateSpecVolumesInnerCsi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecVolumesInnerCsi:
        """Test WarmPoolSpecTemplateSpecVolumesInnerCsi
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecVolumesInnerCsi`
        """
        model = WarmPoolSpecTemplateSpecVolumesInnerCsi()
        if include_optional:
            return WarmPoolSpecTemplateSpecVolumesInnerCsi(
                driver = '',
                fs_type = '',
                node_publish_secret_ref = arl_client.models.warm_pool_spec_template_spec_image_pull_secrets_inner.WarmPoolSpec_template_spec_imagePullSecrets_inner(
                    name = '', ),
                read_only = True,
                volume_attributes = {
                    'key' : ''
                    }
            )
        else:
            return WarmPoolSpecTemplateSpecVolumesInnerCsi(
                driver = '',
        )
        """

    def testWarmPoolSpecTemplateSpecVolumesInnerCsi(self):
        """Test WarmPoolSpecTemplateSpecVolumesInnerCsi"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
