# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.sandbox_spec_resources import SandboxSpecResources

class TestSandboxSpecResources(unittest.TestCase):
    """SandboxSpecResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SandboxSpecResources:
        """Test SandboxSpecResources
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SandboxSpecResources`
        """
        model = SandboxSpecResources()
        if include_optional:
            return SandboxSpecResources(
                claims = [
                    arl_client.models.sandbox_spec_resources_claims_inner.SandboxSpec_resources_claims_inner(
                        name = '', 
                        request = '', )
                    ],
                limits = {
                    'key' : null
                    },
                requests = {
                    'key' : null
                    }
            )
        else:
            return SandboxSpecResources(
        )
        """

    def testSandboxSpecResources(self):
        """Test SandboxSpecResources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
