# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner_pod_certificate import WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInnerPodCertificate

class TestWarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInnerPodCertificate(unittest.TestCase):
    """WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInnerPodCertificate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInnerPodCertificate:
        """Test WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInnerPodCertificate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInnerPodCertificate`
        """
        model = WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInnerPodCertificate()
        if include_optional:
            return WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInnerPodCertificate(
                certificate_chain_path = '',
                credential_bundle_path = '',
                key_path = '',
                key_type = '',
                max_expiration_seconds = 56,
                signer_name = '',
                user_annotations = {
                    'key' : ''
                    }
            )
        else:
            return WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInnerPodCertificate(
                key_type = '',
                signer_name = '',
        )
        """

    def testWarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInnerPodCertificate(self):
        """Test WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInnerPodCertificate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
