# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner import WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInner

class TestWarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInner(unittest.TestCase):
    """WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInner:
        """Test WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInner`
        """
        model = WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInner()
        if include_optional:
            return WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInner(
                cluster_trust_bundle = arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner_cluster_trust_bundle.WarmPoolSpec_template_spec_volumes_inner_projected_sources_inner_clusterTrustBundle(
                    label_selector = arl_client.models.warm_pool_spec_template_spec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector.WarmPoolSpec_template_spec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector(
                        match_expressions = [
                            arl_client.models.warm_pool_spec_template_spec_affinity_node_affinity_preferred_during_scheduling_ignored_during_execution_inner_preference_match_expressions_inner.WarmPoolSpec_template_spec_affinity_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_preference_matchExpressions_inner(
                                key = '', 
                                operator = '', 
                                values = [
                                    ''
                                    ], )
                            ], 
                        match_labels = {
                            'key' : ''
                            }, ), 
                    name = '', 
                    optional = True, 
                    path = '', 
                    signer_name = '', ),
                config_map = arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner_config_map.WarmPoolSpec_template_spec_volumes_inner_projected_sources_inner_configMap(
                    items = [
                        arl_client.models.warm_pool_spec_template_spec_volumes_inner_config_map_items_inner.WarmPoolSpec_template_spec_volumes_inner_configMap_items_inner(
                            key = '', 
                            mode = 56, 
                            path = '', )
                        ], 
                    name = '', 
                    optional = True, ),
                downward_api = arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner_downward_api.WarmPoolSpec_template_spec_volumes_inner_projected_sources_inner_downwardAPI(
                    items = [
                        arl_client.models.warm_pool_spec_template_spec_volumes_inner_downward_api_items_inner.WarmPoolSpec_template_spec_volumes_inner_downwardAPI_items_inner(
                            field_ref = arl_client.models.warm_pool_spec_template_spec_containers_inner_env_inner_value_from_field_ref.WarmPoolSpec_template_spec_containers_inner_env_inner_valueFrom_fieldRef(
                                api_version = '', 
                                field_path = '', ), 
                            mode = 56, 
                            path = '', 
                            resource_field_ref = arl_client.models.warm_pool_spec_template_spec_containers_inner_env_inner_value_from_resource_field_ref.WarmPoolSpec_template_spec_containers_inner_env_inner_valueFrom_resourceFieldRef(
                                container_name = '', 
                                divisor = null, 
                                resource = '', ), )
                        ], ),
                pod_certificate = arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner_pod_certificate.WarmPoolSpec_template_spec_volumes_inner_projected_sources_inner_podCertificate(
                    certificate_chain_path = '', 
                    credential_bundle_path = '', 
                    key_path = '', 
                    key_type = '', 
                    max_expiration_seconds = 56, 
                    signer_name = '', 
                    user_annotations = {
                        'key' : ''
                        }, ),
                secret = arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner_config_map.WarmPoolSpec_template_spec_volumes_inner_projected_sources_inner_configMap(
                    items = [
                        arl_client.models.warm_pool_spec_template_spec_volumes_inner_config_map_items_inner.WarmPoolSpec_template_spec_volumes_inner_configMap_items_inner(
                            key = '', 
                            mode = 56, 
                            path = '', )
                        ], 
                    name = '', 
                    optional = True, ),
                service_account_token = arl_client.models.warm_pool_spec_template_spec_volumes_inner_projected_sources_inner_service_account_token.WarmPoolSpec_template_spec_volumes_inner_projected_sources_inner_serviceAccountToken(
                    audience = '', 
                    expiration_seconds = 56, 
                    path = '', )
            )
        else:
            return WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInner(
        )
        """

    def testWarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInner(self):
        """Test WarmPoolSpecTemplateSpecVolumesInnerProjectedSourcesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
