# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_volumes_inner_secret import WarmPoolSpecTemplateSpecVolumesInnerSecret

class TestWarmPoolSpecTemplateSpecVolumesInnerSecret(unittest.TestCase):
    """WarmPoolSpecTemplateSpecVolumesInnerSecret unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecVolumesInnerSecret:
        """Test WarmPoolSpecTemplateSpecVolumesInnerSecret
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecVolumesInnerSecret`
        """
        model = WarmPoolSpecTemplateSpecVolumesInnerSecret()
        if include_optional:
            return WarmPoolSpecTemplateSpecVolumesInnerSecret(
                default_mode = 56,
                items = [
                    arl_client.models.warm_pool_spec_template_spec_volumes_inner_config_map_items_inner.WarmPoolSpec_template_spec_volumes_inner_configMap_items_inner(
                        key = '', 
                        mode = 56, 
                        path = '', )
                    ],
                optional = True,
                secret_name = ''
            )
        else:
            return WarmPoolSpecTemplateSpecVolumesInnerSecret(
        )
        """

    def testWarmPoolSpecTemplateSpecVolumesInnerSecret(self):
        """Test WarmPoolSpecTemplateSpecVolumesInnerSecret"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
