# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_affinity_pod_affinity import WarmPoolSpecTemplateSpecAffinityPodAffinity

class TestWarmPoolSpecTemplateSpecAffinityPodAffinity(unittest.TestCase):
    """WarmPoolSpecTemplateSpecAffinityPodAffinity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecAffinityPodAffinity:
        """Test WarmPoolSpecTemplateSpecAffinityPodAffinity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecAffinityPodAffinity`
        """
        model = WarmPoolSpecTemplateSpecAffinityPodAffinity()
        if include_optional:
            return WarmPoolSpecTemplateSpecAffinityPodAffinity(
                preferred_during_scheduling_ignored_during_execution = [
                    arl_client.models.warm_pool_spec_template_spec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner.WarmPoolSpec_template_spec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner(
                        pod_affinity_term = arl_client.models.warm_pool_spec_template_spec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term.WarmPoolSpec_template_spec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm(
                            label_selector = arl_client.models.warm_pool_spec_template_spec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector.WarmPoolSpec_template_spec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector(
                                match_expressions = [
                                    arl_client.models.warm_pool_spec_template_spec_affinity_node_affinity_preferred_during_scheduling_ignored_during_execution_inner_preference_match_expressions_inner.WarmPoolSpec_template_spec_affinity_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_preference_matchExpressions_inner(
                                        key = '', 
                                        operator = '', 
                                        values = [
                                            ''
                                            ], )
                                    ], 
                                match_labels = {
                                    'key' : ''
                                    }, ), 
                            match_label_keys = [
                                ''
                                ], 
                            mismatch_label_keys = [
                                ''
                                ], 
                            namespace_selector = arl_client.models.warm_pool_spec_template_spec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector.WarmPoolSpec_template_spec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector(), 
                            namespaces = [
                                ''
                                ], 
                            topology_key = '', ), 
                        weight = 56, )
                    ],
                required_during_scheduling_ignored_during_execution = [
                    arl_client.models.warm_pool_spec_template_spec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term.WarmPoolSpec_template_spec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm(
                        label_selector = arl_client.models.warm_pool_spec_template_spec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector.WarmPoolSpec_template_spec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector(
                            match_expressions = [
                                arl_client.models.warm_pool_spec_template_spec_affinity_node_affinity_preferred_during_scheduling_ignored_during_execution_inner_preference_match_expressions_inner.WarmPoolSpec_template_spec_affinity_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_preference_matchExpressions_inner(
                                    key = '', 
                                    operator = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            match_labels = {
                                'key' : ''
                                }, ), 
                        match_label_keys = [
                            ''
                            ], 
                        mismatch_label_keys = [
                            ''
                            ], 
                        namespace_selector = arl_client.models.warm_pool_spec_template_spec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector.WarmPoolSpec_template_spec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector(), 
                        namespaces = [
                            ''
                            ], 
                        topology_key = '', )
                    ]
            )
        else:
            return WarmPoolSpecTemplateSpecAffinityPodAffinity(
        )
        """

    def testWarmPoolSpecTemplateSpecAffinityPodAffinity(self):
        """Test WarmPoolSpecTemplateSpecAffinityPodAffinity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
