# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.object_meta import ObjectMeta

class TestObjectMeta(unittest.TestCase):
    """ObjectMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObjectMeta:
        """Test ObjectMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObjectMeta`
        """
        model = ObjectMeta()
        if include_optional:
            return ObjectMeta(
                name = '',
                namespace = '',
                labels = {
                    'key' : ''
                    },
                annotations = {
                    'key' : ''
                    }
            )
        else:
            return ObjectMeta(
        )
        """

    def testObjectMeta(self):
        """Test ObjectMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
