# coding: utf-8

"""
    ARL Infrastructure API

    OpenAPI specification for ARL (Agentic RL) Infrastructure custom resources. This SDK provides models for WarmPool, Sandbox, and Task Kubernetes custom resources. 

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arl_client.models.warm_pool_spec_template_spec_volumes_inner_scale_io import WarmPoolSpecTemplateSpecVolumesInnerScaleIO

class TestWarmPoolSpecTemplateSpecVolumesInnerScaleIO(unittest.TestCase):
    """WarmPoolSpecTemplateSpecVolumesInnerScaleIO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarmPoolSpecTemplateSpecVolumesInnerScaleIO:
        """Test WarmPoolSpecTemplateSpecVolumesInnerScaleIO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarmPoolSpecTemplateSpecVolumesInnerScaleIO`
        """
        model = WarmPoolSpecTemplateSpecVolumesInnerScaleIO()
        if include_optional:
            return WarmPoolSpecTemplateSpecVolumesInnerScaleIO(
                fs_type = 'xfs',
                gateway = '',
                protection_domain = '',
                read_only = True,
                secret_ref = arl_client.models.warm_pool_spec_template_spec_image_pull_secrets_inner.WarmPoolSpec_template_spec_imagePullSecrets_inner(
                    name = '', ),
                ssl_enabled = True,
                storage_mode = 'ThinProvisioned',
                storage_pool = '',
                system = '',
                volume_name = ''
            )
        else:
            return WarmPoolSpecTemplateSpecVolumesInnerScaleIO(
                gateway = '',
                secret_ref = arl_client.models.warm_pool_spec_template_spec_image_pull_secrets_inner.WarmPoolSpec_template_spec_imagePullSecrets_inner(
                    name = '', ),
                system = '',
        )
        """

    def testWarmPoolSpecTemplateSpecVolumesInnerScaleIO(self):
        """Test WarmPoolSpecTemplateSpecVolumesInnerScaleIO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
