#!/usr/bin/env bash
set -euo pipefail

PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_DST_DIR="${CODEX_SKILLS_DIR:-$HOME/.codex/skills}"
GENERATED_SKILLS_DIR="${ARL_GENERATED_SKILLS_DIR:-$PLUGIN_DIR/.codex-generated-skills}"
MANAGED_MARKER=".arl-managed.json"
FORCE="${ARL_OVERWRITE_EXISTING:-}"
DRY_RUN=0
NO_GENERATE=0

usage() {
  cat <<EOF
Usage: $0 [--skills-dir DIR] [--force] [--dry-run] [--no-generate]

Install ARL Codex skills into ~/.codex/skills by default.

Options:
  --skills-dir DIR  Install destination (default: \$CODEX_SKILLS_DIR or ~/.codex/skills)
  --force           Overwrite same-named destination skills
  --dry-run         Print actions without copying
  --no-generate     Skip regenerating command compatibility skills
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --skills-dir)
      if [ "$#" -lt 2 ]; then
        echo "Missing value for --skills-dir" >&2
        exit 1
      fi
      SKILLS_DST_DIR="$2"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --no-generate)
      NO_GENERATE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ "$NO_GENERATE" -eq 0 ]; then
  python3 "$PLUGIN_DIR/scripts/build_codex_compat_skills.py" \
    --repo-root "$PLUGIN_DIR" \
    --out-dir "$GENERATED_SKILLS_DIR" \
    --clean
fi

if [ "$DRY_RUN" -eq 0 ]; then
  mkdir -p "$SKILLS_DST_DIR"
fi

declare -A SEEN_SOURCES=()
INSTALLED=()
UPDATED=()
SKIPPED=()

is_truthy() {
  case "${1:-}" in
    1|true|TRUE|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

can_update() {
  local dst="$1"

  if is_truthy "$FORCE"; then
    return 0
  fi
  if [ -L "$dst" ]; then
    return 0
  fi
  if [ -f "$dst/$MANAGED_MARKER" ] && grep -q '"manager": "arl"' "$dst/$MANAGED_MARKER"; then
    return 0
  fi
  if [ -f "$dst/SKILL.md" ] && grep -q 'Generated by scripts/build_codex_compat_skills.py' "$dst/SKILL.md"; then
    return 0
  fi

  return 1
}

write_marker() {
  local dst="$1"
  local src="$2"
  local rel="$src"

  case "$src" in
    "$PLUGIN_DIR"/*) rel="${src#"$PLUGIN_DIR"/}" ;;
  esac

  cat > "$dst/$MANAGED_MARKER" <<EOF
{
  "manager": "arl",
  "source": "$rel",
  "source_name": "$(basename "$src")"
}
EOF
}

copy_skill() {
  local src="$1"
  local dst="$2"

  if [ "$DRY_RUN" -eq 1 ]; then
    return 0
  fi

  rm -rf -- "$dst"
  cp -R "$src" "$dst"
  write_marker "$dst" "$src"
}

install_from_root() {
  local src_root="$1"

  [ -d "$src_root" ] || return 0

  local src
  for src in "$src_root"/*; do
    [ -d "$src" ] || continue
    [ -f "$src/SKILL.md" ] || continue

    local name
    name="$(basename "$src")"
    if [ -n "${SEEN_SOURCES[$name]:-}" ]; then
      SKIPPED+=("$name: duplicate-source-name: ${SEEN_SOURCES[$name]}")
      continue
    fi
    SEEN_SOURCES[$name]="$src"

    local dst="$SKILLS_DST_DIR/$name"
    if [ -e "$dst" ] && [ ! -f "$dst/SKILL.md" ]; then
      SKIPPED+=("$name: destination-exists-without-SKILL.md")
      continue
    fi

    if [ -e "$dst" ]; then
      if can_update "$dst"; then
        copy_skill "$src" "$dst"
        UPDATED+=("$name")
      else
        SKIPPED+=("$name: destination-managed-elsewhere")
      fi
    else
      copy_skill "$src" "$dst"
      INSTALLED+=("$name")
    fi
  done
}

join_or_none() {
  if [ "$#" -eq 0 ]; then
    printf '<none>'
    return
  fi
  local first=1
  local item
  for item in "$@"; do
    if [ "$first" -eq 1 ]; then
      first=0
    else
      printf ', '
    fi
    printf '%s' "$item"
  done
}

install_from_root "$PLUGIN_DIR/skills"
install_from_root "$GENERATED_SKILLS_DIR"

if [ "$DRY_RUN" -eq 1 ]; then
  echo "Would install ARL Codex skills into: $SKILLS_DST_DIR"
else
  echo "Installed ARL Codex skills into: $SKILLS_DST_DIR"
fi
echo "Installed: $(join_or_none "${INSTALLED[@]}")"
echo "Updated: $(join_or_none "${UPDATED[@]}")"
if [ "${#SKIPPED[@]}" -eq 0 ]; then
  echo "Skipped: <none>"
else
  echo "Skipped:"
  for item in "${SKIPPED[@]}"; do
    echo "  - $item"
  done
fi
