# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from arl.pb.proto import agent_pb2 as proto_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """AgentService provides file operations, process control, and environment management
    Note: RPC method numbers 6-20 are reserved for future observation interfaces
    (e.g., ReadFile, ListDirectory, GetProcessStatus, etc.)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateFiles = channel.unary_unary(
                '/arl.sidecar.AgentService/UpdateFiles',
                request_serializer=proto_dot_agent__pb2.FileRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.FileResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_stream(
                '/arl.sidecar.AgentService/Execute',
                request_serializer=proto_dot_agent__pb2.ExecRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.ExecLog.FromString,
                _registered_method=True)
        self.SignalProcess = channel.unary_unary(
                '/arl.sidecar.AgentService/SignalProcess',
                request_serializer=proto_dot_agent__pb2.SignalRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.SignalResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/arl.sidecar.AgentService/Reset',
                request_serializer=proto_dot_agent__pb2.ResetRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.InteractiveShell = channel.stream_stream(
                '/arl.sidecar.AgentService/InteractiveShell',
                request_serializer=proto_dot_agent__pb2.ShellInput.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.ShellOutput.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """AgentService provides file operations, process control, and environment management
    Note: RPC method numbers 6-20 are reserved for future observation interfaces
    (e.g., ReadFile, ListDirectory, GetProcessStatus, etc.)
    """

    def UpdateFiles(self, request, context):
        """UpdateFiles applies file patches or overwrites
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Execute runs a command (Job mode) or starts a background service (Service mode)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignalProcess(self, request, context):
        """SignalProcess sends signals (SIGTERM/SIGKILL) to processes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset cleans the workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InteractiveShell(self, request_iterator, context):
        """InteractiveShell provides bidirectional streaming for interactive shell sessions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFiles,
                    request_deserializer=proto_dot_agent__pb2.FileRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.FileResponse.SerializeToString,
            ),
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=proto_dot_agent__pb2.ExecRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.ExecLog.SerializeToString,
            ),
            'SignalProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.SignalProcess,
                    request_deserializer=proto_dot_agent__pb2.SignalRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.SignalResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=proto_dot_agent__pb2.ResetRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.ResetResponse.SerializeToString,
            ),
            'InteractiveShell': grpc.stream_stream_rpc_method_handler(
                    servicer.InteractiveShell,
                    request_deserializer=proto_dot_agent__pb2.ShellInput.FromString,
                    response_serializer=proto_dot_agent__pb2.ShellOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arl.sidecar.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arl.sidecar.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """AgentService provides file operations, process control, and environment management
    Note: RPC method numbers 6-20 are reserved for future observation interfaces
    (e.g., ReadFile, ListDirectory, GetProcessStatus, etc.)
    """

    @staticmethod
    def UpdateFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arl.sidecar.AgentService/UpdateFiles',
            proto_dot_agent__pb2.FileRequest.SerializeToString,
            proto_dot_agent__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arl.sidecar.AgentService/Execute',
            proto_dot_agent__pb2.ExecRequest.SerializeToString,
            proto_dot_agent__pb2.ExecLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignalProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arl.sidecar.AgentService/SignalProcess',
            proto_dot_agent__pb2.SignalRequest.SerializeToString,
            proto_dot_agent__pb2.SignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arl.sidecar.AgentService/Reset',
            proto_dot_agent__pb2.ResetRequest.SerializeToString,
            proto_dot_agent__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InteractiveShell(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/arl.sidecar.AgentService/InteractiveShell',
            proto_dot_agent__pb2.ShellInput.SerializeToString,
            proto_dot_agent__pb2.ShellOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
