// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/executor_v2.proto

package executorv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request is the top-level multiplexed client-to-server frame.
// Each request carries a correlation tag returned verbatim in the
// matching Response or subsequent Events.
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tag   uint32                 `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Request_Ping
	//	*Request_Spawn
	//	*Request_WriteIn
	//	*Request_Signal
	//	*Request_Resize
	//	*Request_Read
	//	*Request_Write
	//	*Request_Stat
	//	*Request_List
	//	*Request_Tunnel
	//	*Request_Watch
	//	*Request_Unwatch
	//	*Request_CloseTunnel
	//	*Request_ListTunnels
	Kind          isRequest_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_executor_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetTag() uint32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *Request) GetKind() isRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Request) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Request) GetSpawn() *SpawnRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Spawn); ok {
			return x.Spawn
		}
	}
	return nil
}

func (x *Request) GetWriteIn() *WriteInRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_WriteIn); ok {
			return x.WriteIn
		}
	}
	return nil
}

func (x *Request) GetSignal() *SignalRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *Request) GetResize() *ResizeRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *Request) GetRead() *ReadRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Request) GetWrite() *WriteRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Write); ok {
			return x.Write
		}
	}
	return nil
}

func (x *Request) GetStat() *StatRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Stat); ok {
			return x.Stat
		}
	}
	return nil
}

func (x *Request) GetList() *ListRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Request) GetTunnel() *TunnelRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Tunnel); ok {
			return x.Tunnel
		}
	}
	return nil
}

func (x *Request) GetWatch() *WatchRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Watch); ok {
			return x.Watch
		}
	}
	return nil
}

func (x *Request) GetUnwatch() *UnwatchRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Unwatch); ok {
			return x.Unwatch
		}
	}
	return nil
}

func (x *Request) GetCloseTunnel() *CloseTunnelRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_CloseTunnel); ok {
			return x.CloseTunnel
		}
	}
	return nil
}

func (x *Request) GetListTunnels() *ListTunnelsRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_ListTunnels); ok {
			return x.ListTunnels
		}
	}
	return nil
}

type isRequest_Kind interface {
	isRequest_Kind()
}

type Request_Ping struct {
	Ping *PingRequest `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type Request_Spawn struct {
	Spawn *SpawnRequest `protobuf:"bytes,3,opt,name=spawn,proto3,oneof"`
}

type Request_WriteIn struct {
	WriteIn *WriteInRequest `protobuf:"bytes,4,opt,name=write_in,json=writeIn,proto3,oneof"`
}

type Request_Signal struct {
	Signal *SignalRequest `protobuf:"bytes,5,opt,name=signal,proto3,oneof"`
}

type Request_Resize struct {
	Resize *ResizeRequest `protobuf:"bytes,6,opt,name=resize,proto3,oneof"`
}

type Request_Read struct {
	Read *ReadRequest `protobuf:"bytes,7,opt,name=read,proto3,oneof"`
}

type Request_Write struct {
	Write *WriteRequest `protobuf:"bytes,8,opt,name=write,proto3,oneof"`
}

type Request_Stat struct {
	Stat *StatRequest `protobuf:"bytes,9,opt,name=stat,proto3,oneof"`
}

type Request_List struct {
	List *ListRequest `protobuf:"bytes,10,opt,name=list,proto3,oneof"`
}

type Request_Tunnel struct {
	Tunnel *TunnelRequest `protobuf:"bytes,11,opt,name=tunnel,proto3,oneof"`
}

type Request_Watch struct {
	Watch *WatchRequest `protobuf:"bytes,12,opt,name=watch,proto3,oneof"`
}

type Request_Unwatch struct {
	Unwatch *UnwatchRequest `protobuf:"bytes,13,opt,name=unwatch,proto3,oneof"`
}

type Request_CloseTunnel struct {
	CloseTunnel *CloseTunnelRequest `protobuf:"bytes,14,opt,name=close_tunnel,json=closeTunnel,proto3,oneof"`
}

type Request_ListTunnels struct {
	ListTunnels *ListTunnelsRequest `protobuf:"bytes,15,opt,name=list_tunnels,json=listTunnels,proto3,oneof"`
}

func (*Request_Ping) isRequest_Kind() {}

func (*Request_Spawn) isRequest_Kind() {}

func (*Request_WriteIn) isRequest_Kind() {}

func (*Request_Signal) isRequest_Kind() {}

func (*Request_Resize) isRequest_Kind() {}

func (*Request_Read) isRequest_Kind() {}

func (*Request_Write) isRequest_Kind() {}

func (*Request_Stat) isRequest_Kind() {}

func (*Request_List) isRequest_Kind() {}

func (*Request_Tunnel) isRequest_Kind() {}

func (*Request_Watch) isRequest_Kind() {}

func (*Request_Unwatch) isRequest_Kind() {}

func (*Request_CloseTunnel) isRequest_Kind() {}

func (*Request_ListTunnels) isRequest_Kind() {}

// Response is the top-level server-to-client reply frame.
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tag   uint32                 `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Response_Ping
	//	*Response_Spawn
	//	*Response_WriteIn
	//	*Response_Signal
	//	*Response_Resize
	//	*Response_Read
	//	*Response_Write
	//	*Response_Stat
	//	*Response_List
	//	*Response_Tunnel
	//	*Response_Watch
	//	*Response_Unwatch
	//	*Response_Error
	//	*Response_CloseTunnel
	//	*Response_ListTunnels
	Kind          isResponse_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_executor_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetTag() uint32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *Response) GetKind() isResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Response) GetPing() *PingResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Response) GetSpawn() *SpawnResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Spawn); ok {
			return x.Spawn
		}
	}
	return nil
}

func (x *Response) GetWriteIn() *WriteInResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_WriteIn); ok {
			return x.WriteIn
		}
	}
	return nil
}

func (x *Response) GetSignal() *SignalResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *Response) GetResize() *ResizeResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *Response) GetRead() *ReadResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Response) GetWrite() *WriteResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Write); ok {
			return x.Write
		}
	}
	return nil
}

func (x *Response) GetStat() *StatResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Stat); ok {
			return x.Stat
		}
	}
	return nil
}

func (x *Response) GetList() *ListResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Response) GetTunnel() *TunnelResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Tunnel); ok {
			return x.Tunnel
		}
	}
	return nil
}

func (x *Response) GetWatch() *WatchResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Watch); ok {
			return x.Watch
		}
	}
	return nil
}

func (x *Response) GetUnwatch() *UnwatchResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Unwatch); ok {
			return x.Unwatch
		}
	}
	return nil
}

func (x *Response) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Response) GetCloseTunnel() *CloseTunnelResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_CloseTunnel); ok {
			return x.CloseTunnel
		}
	}
	return nil
}

func (x *Response) GetListTunnels() *ListTunnelsResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_ListTunnels); ok {
			return x.ListTunnels
		}
	}
	return nil
}

type isResponse_Kind interface {
	isResponse_Kind()
}

type Response_Ping struct {
	Ping *PingResponse `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type Response_Spawn struct {
	Spawn *SpawnResponse `protobuf:"bytes,3,opt,name=spawn,proto3,oneof"`
}

type Response_WriteIn struct {
	WriteIn *WriteInResponse `protobuf:"bytes,4,opt,name=write_in,json=writeIn,proto3,oneof"`
}

type Response_Signal struct {
	Signal *SignalResponse `protobuf:"bytes,5,opt,name=signal,proto3,oneof"`
}

type Response_Resize struct {
	Resize *ResizeResponse `protobuf:"bytes,6,opt,name=resize,proto3,oneof"`
}

type Response_Read struct {
	Read *ReadResponse `protobuf:"bytes,7,opt,name=read,proto3,oneof"`
}

type Response_Write struct {
	Write *WriteResponse `protobuf:"bytes,8,opt,name=write,proto3,oneof"`
}

type Response_Stat struct {
	Stat *StatResponse `protobuf:"bytes,9,opt,name=stat,proto3,oneof"`
}

type Response_List struct {
	List *ListResponse `protobuf:"bytes,10,opt,name=list,proto3,oneof"`
}

type Response_Tunnel struct {
	Tunnel *TunnelResponse `protobuf:"bytes,11,opt,name=tunnel,proto3,oneof"`
}

type Response_Watch struct {
	Watch *WatchResponse `protobuf:"bytes,12,opt,name=watch,proto3,oneof"`
}

type Response_Unwatch struct {
	Unwatch *UnwatchResponse `protobuf:"bytes,13,opt,name=unwatch,proto3,oneof"`
}

type Response_Error struct {
	Error *ErrorResponse `protobuf:"bytes,14,opt,name=error,proto3,oneof"`
}

type Response_CloseTunnel struct {
	CloseTunnel *CloseTunnelResponse `protobuf:"bytes,15,opt,name=close_tunnel,json=closeTunnel,proto3,oneof"`
}

type Response_ListTunnels struct {
	ListTunnels *ListTunnelsResponse `protobuf:"bytes,16,opt,name=list_tunnels,json=listTunnels,proto3,oneof"`
}

func (*Response_Ping) isResponse_Kind() {}

func (*Response_Spawn) isResponse_Kind() {}

func (*Response_WriteIn) isResponse_Kind() {}

func (*Response_Signal) isResponse_Kind() {}

func (*Response_Resize) isResponse_Kind() {}

func (*Response_Read) isResponse_Kind() {}

func (*Response_Write) isResponse_Kind() {}

func (*Response_Stat) isResponse_Kind() {}

func (*Response_List) isResponse_Kind() {}

func (*Response_Tunnel) isResponse_Kind() {}

func (*Response_Watch) isResponse_Kind() {}

func (*Response_Unwatch) isResponse_Kind() {}

func (*Response_Error) isResponse_Kind() {}

func (*Response_CloseTunnel) isResponse_Kind() {}

func (*Response_ListTunnels) isResponse_Kind() {}

// Event is a server-pushed frame for asynchronous notifications.
// Four event types only; tunnel and file data flow as raw bytes on
// dedicated streams, not as protobuf Events.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tag   uint32                 `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Event_Stdout
	//	*Event_Stderr
	//	*Event_Exit
	//	*Event_FsChange
	Kind          isEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_executor_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetTag() uint32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *Event) GetKind() isEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Event) GetStdout() *StdoutEvent {
	if x != nil {
		if x, ok := x.Kind.(*Event_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *Event) GetStderr() *StderrEvent {
	if x != nil {
		if x, ok := x.Kind.(*Event_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *Event) GetExit() *ExitEvent {
	if x != nil {
		if x, ok := x.Kind.(*Event_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *Event) GetFsChange() *FsChangeEvent {
	if x != nil {
		if x, ok := x.Kind.(*Event_FsChange); ok {
			return x.FsChange
		}
	}
	return nil
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_Stdout struct {
	Stdout *StdoutEvent `protobuf:"bytes,2,opt,name=stdout,proto3,oneof"`
}

type Event_Stderr struct {
	Stderr *StderrEvent `protobuf:"bytes,3,opt,name=stderr,proto3,oneof"`
}

type Event_Exit struct {
	Exit *ExitEvent `protobuf:"bytes,4,opt,name=exit,proto3,oneof"`
}

type Event_FsChange struct {
	FsChange *FsChangeEvent `protobuf:"bytes,5,opt,name=fs_change,json=fsChange,proto3,oneof"`
}

func (*Event_Stdout) isEvent_Kind() {}

func (*Event_Stderr) isEvent_Kind() {}

func (*Event_Exit) isEvent_Kind() {}

func (*Event_FsChange) isEvent_Kind() {}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{3}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{4}
}

type SpawnRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	Env            map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir     string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Pty            bool                   `protobuf:"varint,5,opt,name=pty,proto3" json:"pty,omitempty"`
	Stdin          bool                   `protobuf:"varint,6,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Rows           int32                  `protobuf:"varint,7,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols           int32                  `protobuf:"varint,8,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpawnRequest) Reset() {
	*x = SpawnRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnRequest) ProtoMessage() {}

func (x *SpawnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnRequest.ProtoReflect.Descriptor instead.
func (*SpawnRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{5}
}

func (x *SpawnRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SpawnRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SpawnRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *SpawnRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *SpawnRequest) GetPty() bool {
	if x != nil {
		return x.Pty
	}
	return false
}

func (x *SpawnRequest) GetStdin() bool {
	if x != nil {
		return x.Stdin
	}
	return false
}

func (x *SpawnRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *SpawnRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type SpawnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessTag    uint32                 `protobuf:"varint,1,opt,name=process_tag,json=processTag,proto3" json:"process_tag,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnResponse) Reset() {
	*x = SpawnResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnResponse) ProtoMessage() {}

func (x *SpawnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnResponse.ProtoReflect.Descriptor instead.
func (*SpawnResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{6}
}

func (x *SpawnResponse) GetProcessTag() uint32 {
	if x != nil {
		return x.ProcessTag
	}
	return 0
}

func (x *SpawnResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type WriteInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessTag    uint32                 `protobuf:"varint,1,opt,name=process_tag,json=processTag,proto3" json:"process_tag,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteInRequest) Reset() {
	*x = WriteInRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteInRequest) ProtoMessage() {}

func (x *WriteInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteInRequest.ProtoReflect.Descriptor instead.
func (*WriteInRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{7}
}

func (x *WriteInRequest) GetProcessTag() uint32 {
	if x != nil {
		return x.ProcessTag
	}
	return 0
}

func (x *WriteInRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteInResponse) Reset() {
	*x = WriteInResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteInResponse) ProtoMessage() {}

func (x *WriteInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteInResponse.ProtoReflect.Descriptor instead.
func (*WriteInResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{8}
}

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessTag    uint32                 `protobuf:"varint,1,opt,name=process_tag,json=processTag,proto3" json:"process_tag,omitempty"`
	Signal        string                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{9}
}

func (x *SignalRequest) GetProcessTag() uint32 {
	if x != nil {
		return x.ProcessTag
	}
	return 0
}

func (x *SignalRequest) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{10}
}

type ResizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessTag    uint32                 `protobuf:"varint,1,opt,name=process_tag,json=processTag,proto3" json:"process_tag,omitempty"`
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeRequest) Reset() {
	*x = ResizeRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeRequest) ProtoMessage() {}

func (x *ResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeRequest.ProtoReflect.Descriptor instead.
func (*ResizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{11}
}

func (x *ResizeRequest) GetProcessTag() uint32 {
	if x != nil {
		return x.ProcessTag
	}
	return 0
}

func (x *ResizeRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ResizeRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type ResizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeResponse) Reset() {
	*x = ResizeResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeResponse) ProtoMessage() {}

func (x *ResizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeResponse.ProtoReflect.Descriptor instead.
func (*ResizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{12}
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{13}
}

func (x *ReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SizeBytes     int64                  `protobuf:"varint,1,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{14}
}

func (x *ReadResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ReadResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type WriteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ExpectedSha256 string                 `protobuf:"bytes,2,opt,name=expected_sha256,json=expectedSha256,proto3" json:"expected_sha256,omitempty"`
	SizeHint       int64                  `protobuf:"varint,3,opt,name=size_hint,json=sizeHint,proto3" json:"size_hint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{15}
}

func (x *WriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteRequest) GetExpectedSha256() string {
	if x != nil {
		return x.ExpectedSha256
	}
	return ""
}

func (x *WriteRequest) GetSizeHint() int64 {
	if x != nil {
		return x.SizeHint
	}
	return 0
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{16}
}

func (x *WriteResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *WriteResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{17}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTimeUnix   int64                  `protobuf:"varint,4,opt,name=mod_time_unix,json=modTimeUnix,proto3" json:"mod_time_unix,omitempty"`
	IsDir         bool                   `protobuf:"varint,5,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{18}
}

func (x *StatResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StatResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *StatResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StatResponse) GetModTimeUnix() int64 {
	if x != nil {
		return x.ModTimeUnix
	}
	return 0
}

func (x *StatResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{19}
}

func (x *ListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{20}
}

func (x *ListResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTimeUnix   int64                  `protobuf:"varint,4,opt,name=mod_time_unix,json=modTimeUnix,proto3" json:"mod_time_unix,omitempty"`
	IsDir         bool                   `protobuf:"varint,5,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_proto_executor_v2_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{21}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DirEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *DirEntry) GetModTimeUnix() int64 {
	if x != nil {
		return x.ModTimeUnix
	}
	return 0
}

func (x *DirEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type TunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelRequest) Reset() {
	*x = TunnelRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelRequest) ProtoMessage() {}

func (x *TunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelRequest.ProtoReflect.Descriptor instead.
func (*TunnelRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{22}
}

func (x *TunnelRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TunnelRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type TunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelResponse) Reset() {
	*x = TunnelResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelResponse) ProtoMessage() {}

func (x *TunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelResponse.ProtoReflect.Descriptor instead.
func (*TunnelResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{23}
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	EventTypes    []string               `protobuf:"bytes,3,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{24}
}

func (x *WatchRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WatchRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *WatchRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WatchId       uint32                 `protobuf:"varint,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{25}
}

func (x *WatchResponse) GetWatchId() uint32 {
	if x != nil {
		return x.WatchId
	}
	return 0
}

type UnwatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WatchId       uint32                 `protobuf:"varint,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwatchRequest) Reset() {
	*x = UnwatchRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwatchRequest) ProtoMessage() {}

func (x *UnwatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwatchRequest.ProtoReflect.Descriptor instead.
func (*UnwatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{26}
}

func (x *UnwatchRequest) GetWatchId() uint32 {
	if x != nil {
		return x.WatchId
	}
	return 0
}

type UnwatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwatchResponse) Reset() {
	*x = UnwatchResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwatchResponse) ProtoMessage() {}

func (x *UnwatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwatchResponse.ProtoReflect.Descriptor instead.
func (*UnwatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{27}
}

type CloseTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelTag     uint32                 `protobuf:"varint,1,opt,name=tunnel_tag,json=tunnelTag,proto3" json:"tunnel_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTunnelRequest) Reset() {
	*x = CloseTunnelRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnelRequest) ProtoMessage() {}

func (x *CloseTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnelRequest.ProtoReflect.Descriptor instead.
func (*CloseTunnelRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{28}
}

func (x *CloseTunnelRequest) GetTunnelTag() uint32 {
	if x != nil {
		return x.TunnelTag
	}
	return 0
}

type CloseTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTunnelResponse) Reset() {
	*x = CloseTunnelResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnelResponse) ProtoMessage() {}

func (x *CloseTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnelResponse.ProtoReflect.Descriptor instead.
func (*CloseTunnelResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{29}
}

type ListTunnelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsRequest) Reset() {
	*x = ListTunnelsRequest{}
	mi := &file_proto_executor_v2_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsRequest) ProtoMessage() {}

func (x *ListTunnelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsRequest.ProtoReflect.Descriptor instead.
func (*ListTunnelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{30}
}

type ListTunnelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnels       []*TunnelInfo          `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsResponse) Reset() {
	*x = ListTunnelsResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsResponse) ProtoMessage() {}

func (x *ListTunnelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsResponse.ProtoReflect.Descriptor instead.
func (*ListTunnelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{31}
}

func (x *ListTunnelsResponse) GetTunnels() []*TunnelInfo {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

type TunnelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           uint32                 `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelInfo) Reset() {
	*x = TunnelInfo{}
	mi := &file_proto_executor_v2_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelInfo) ProtoMessage() {}

func (x *TunnelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelInfo.ProtoReflect.Descriptor instead.
func (*TunnelInfo) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{32}
}

func (x *TunnelInfo) GetTag() uint32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *TunnelInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TunnelInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_executor_v2_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{33}
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StdoutEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessTag    uint32                 `protobuf:"varint,1,opt,name=process_tag,json=processTag,proto3" json:"process_tag,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdoutEvent) Reset() {
	*x = StdoutEvent{}
	mi := &file_proto_executor_v2_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdoutEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdoutEvent) ProtoMessage() {}

func (x *StdoutEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdoutEvent.ProtoReflect.Descriptor instead.
func (*StdoutEvent) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{34}
}

func (x *StdoutEvent) GetProcessTag() uint32 {
	if x != nil {
		return x.ProcessTag
	}
	return 0
}

func (x *StdoutEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StderrEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessTag    uint32                 `protobuf:"varint,1,opt,name=process_tag,json=processTag,proto3" json:"process_tag,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StderrEvent) Reset() {
	*x = StderrEvent{}
	mi := &file_proto_executor_v2_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StderrEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StderrEvent) ProtoMessage() {}

func (x *StderrEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StderrEvent.ProtoReflect.Descriptor instead.
func (*StderrEvent) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{35}
}

func (x *StderrEvent) GetProcessTag() uint32 {
	if x != nil {
		return x.ProcessTag
	}
	return 0
}

func (x *StderrEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExitEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessTag    uint32                 `protobuf:"varint,1,opt,name=process_tag,json=processTag,proto3" json:"process_tag,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitEvent) Reset() {
	*x = ExitEvent{}
	mi := &file_proto_executor_v2_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitEvent) ProtoMessage() {}

func (x *ExitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitEvent.ProtoReflect.Descriptor instead.
func (*ExitEvent) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{36}
}

func (x *ExitEvent) GetProcessTag() uint32 {
	if x != nil {
		return x.ProcessTag
	}
	return 0
}

func (x *ExitEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type FsChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WatchId       uint32                 `protobuf:"varint,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsChangeEvent) Reset() {
	*x = FsChangeEvent{}
	mi := &file_proto_executor_v2_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsChangeEvent) ProtoMessage() {}

func (x *FsChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_v2_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsChangeEvent.ProtoReflect.Descriptor instead.
func (*FsChangeEvent) Descriptor() ([]byte, []int) {
	return file_proto_executor_v2_proto_rawDescGZIP(), []int{37}
}

func (x *FsChangeEvent) GetWatchId() uint32 {
	if x != nil {
		return x.WatchId
	}
	return 0
}

func (x *FsChangeEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FsChangeEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

var File_proto_executor_v2_proto protoreflect.FileDescriptor

const file_proto_executor_v2_proto_rawDesc = "" +
	"\n" +
	"\x17proto/executor_v2.proto\x12\x0farl.executor.v2\"\xd5\x06\n" +
	"\aRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\rR\x03tag\x122\n" +
	"\x04ping\x18\x02 \x01(\v2\x1c.arl.executor.v2.PingRequestH\x00R\x04ping\x125\n" +
	"\x05spawn\x18\x03 \x01(\v2\x1d.arl.executor.v2.SpawnRequestH\x00R\x05spawn\x12<\n" +
	"\bwrite_in\x18\x04 \x01(\v2\x1f.arl.executor.v2.WriteInRequestH\x00R\awriteIn\x128\n" +
	"\x06signal\x18\x05 \x01(\v2\x1e.arl.executor.v2.SignalRequestH\x00R\x06signal\x128\n" +
	"\x06resize\x18\x06 \x01(\v2\x1e.arl.executor.v2.ResizeRequestH\x00R\x06resize\x122\n" +
	"\x04read\x18\a \x01(\v2\x1c.arl.executor.v2.ReadRequestH\x00R\x04read\x125\n" +
	"\x05write\x18\b \x01(\v2\x1d.arl.executor.v2.WriteRequestH\x00R\x05write\x122\n" +
	"\x04stat\x18\t \x01(\v2\x1c.arl.executor.v2.StatRequestH\x00R\x04stat\x122\n" +
	"\x04list\x18\n" +
	" \x01(\v2\x1c.arl.executor.v2.ListRequestH\x00R\x04list\x128\n" +
	"\x06tunnel\x18\v \x01(\v2\x1e.arl.executor.v2.TunnelRequestH\x00R\x06tunnel\x125\n" +
	"\x05watch\x18\f \x01(\v2\x1d.arl.executor.v2.WatchRequestH\x00R\x05watch\x12;\n" +
	"\aunwatch\x18\r \x01(\v2\x1f.arl.executor.v2.UnwatchRequestH\x00R\aunwatch\x12H\n" +
	"\fclose_tunnel\x18\x0e \x01(\v2#.arl.executor.v2.CloseTunnelRequestH\x00R\vcloseTunnel\x12H\n" +
	"\flist_tunnels\x18\x0f \x01(\v2#.arl.executor.v2.ListTunnelsRequestH\x00R\vlistTunnelsB\x06\n" +
	"\x04kind\"\x9c\a\n" +
	"\bResponse\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\rR\x03tag\x123\n" +
	"\x04ping\x18\x02 \x01(\v2\x1d.arl.executor.v2.PingResponseH\x00R\x04ping\x126\n" +
	"\x05spawn\x18\x03 \x01(\v2\x1e.arl.executor.v2.SpawnResponseH\x00R\x05spawn\x12=\n" +
	"\bwrite_in\x18\x04 \x01(\v2 .arl.executor.v2.WriteInResponseH\x00R\awriteIn\x129\n" +
	"\x06signal\x18\x05 \x01(\v2\x1f.arl.executor.v2.SignalResponseH\x00R\x06signal\x129\n" +
	"\x06resize\x18\x06 \x01(\v2\x1f.arl.executor.v2.ResizeResponseH\x00R\x06resize\x123\n" +
	"\x04read\x18\a \x01(\v2\x1d.arl.executor.v2.ReadResponseH\x00R\x04read\x126\n" +
	"\x05write\x18\b \x01(\v2\x1e.arl.executor.v2.WriteResponseH\x00R\x05write\x123\n" +
	"\x04stat\x18\t \x01(\v2\x1d.arl.executor.v2.StatResponseH\x00R\x04stat\x123\n" +
	"\x04list\x18\n" +
	" \x01(\v2\x1d.arl.executor.v2.ListResponseH\x00R\x04list\x129\n" +
	"\x06tunnel\x18\v \x01(\v2\x1f.arl.executor.v2.TunnelResponseH\x00R\x06tunnel\x126\n" +
	"\x05watch\x18\f \x01(\v2\x1e.arl.executor.v2.WatchResponseH\x00R\x05watch\x12<\n" +
	"\aunwatch\x18\r \x01(\v2 .arl.executor.v2.UnwatchResponseH\x00R\aunwatch\x126\n" +
	"\x05error\x18\x0e \x01(\v2\x1e.arl.executor.v2.ErrorResponseH\x00R\x05error\x12I\n" +
	"\fclose_tunnel\x18\x0f \x01(\v2$.arl.executor.v2.CloseTunnelResponseH\x00R\vcloseTunnel\x12I\n" +
	"\flist_tunnels\x18\x10 \x01(\v2$.arl.executor.v2.ListTunnelsResponseH\x00R\vlistTunnelsB\x06\n" +
	"\x04kind\"\x82\x02\n" +
	"\x05Event\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\rR\x03tag\x126\n" +
	"\x06stdout\x18\x02 \x01(\v2\x1c.arl.executor.v2.StdoutEventH\x00R\x06stdout\x126\n" +
	"\x06stderr\x18\x03 \x01(\v2\x1c.arl.executor.v2.StderrEventH\x00R\x06stderr\x120\n" +
	"\x04exit\x18\x04 \x01(\v2\x1a.arl.executor.v2.ExitEventH\x00R\x04exit\x12=\n" +
	"\tfs_change\x18\x05 \x01(\v2\x1e.arl.executor.v2.FsChangeEventH\x00R\bfsChangeB\x06\n" +
	"\x04kind\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"\xb4\x02\n" +
	"\fSpawnRequest\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x128\n" +
	"\x03env\x18\x02 \x03(\v2&.arl.executor.v2.SpawnRequest.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12\x10\n" +
	"\x03pty\x18\x05 \x01(\bR\x03pty\x12\x14\n" +
	"\x05stdin\x18\x06 \x01(\bR\x05stdin\x12\x12\n" +
	"\x04rows\x18\a \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\b \x01(\x05R\x04cols\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\rSpawnResponse\x12\x1f\n" +
	"\vprocess_tag\x18\x01 \x01(\rR\n" +
	"processTag\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\"E\n" +
	"\x0eWriteInRequest\x12\x1f\n" +
	"\vprocess_tag\x18\x01 \x01(\rR\n" +
	"processTag\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x11\n" +
	"\x0fWriteInResponse\"H\n" +
	"\rSignalRequest\x12\x1f\n" +
	"\vprocess_tag\x18\x01 \x01(\rR\n" +
	"processTag\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\"\x10\n" +
	"\x0eSignalResponse\"X\n" +
	"\rResizeRequest\x12\x1f\n" +
	"\vprocess_tag\x18\x01 \x01(\rR\n" +
	"processTag\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\x05R\x04cols\"\x10\n" +
	"\x0eResizeResponse\"!\n" +
	"\vReadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"E\n" +
	"\fReadResponse\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x01 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"h\n" +
	"\fWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12'\n" +
	"\x0fexpected_sha256\x18\x02 \x01(\tR\x0eexpectedSha256\x12\x1b\n" +
	"\tsize_hint\x18\x03 \x01(\x03R\bsizeHint\"L\n" +
	"\rWriteResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x90\x01\n" +
	"\fStatResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\"\n" +
	"\rmod_time_unix\x18\x04 \x01(\x03R\vmodTimeUnix\x12\x15\n" +
	"\x06is_dir\x18\x05 \x01(\bR\x05isDir\"?\n" +
	"\vListRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"C\n" +
	"\fListResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.arl.executor.v2.DirEntryR\aentries\"\x8c\x01\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\"\n" +
	"\rmod_time_unix\x18\x04 \x01(\x03R\vmodTimeUnix\x12\x15\n" +
	"\x06is_dir\x18\x05 \x01(\bR\x05isDir\"7\n" +
	"\rTunnelRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\x10\n" +
	"\x0eTunnelResponse\"a\n" +
	"\fWatchRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\x12\x1f\n" +
	"\vevent_types\x18\x03 \x03(\tR\n" +
	"eventTypes\"*\n" +
	"\rWatchResponse\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\rR\awatchId\"+\n" +
	"\x0eUnwatchRequest\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\rR\awatchId\"\x11\n" +
	"\x0fUnwatchResponse\"3\n" +
	"\x12CloseTunnelRequest\x12\x1d\n" +
	"\n" +
	"tunnel_tag\x18\x01 \x01(\rR\ttunnelTag\"\x15\n" +
	"\x13CloseTunnelResponse\"\x14\n" +
	"\x12ListTunnelsRequest\"L\n" +
	"\x13ListTunnelsResponse\x125\n" +
	"\atunnels\x18\x01 \x03(\v2\x1b.arl.executor.v2.TunnelInfoR\atunnels\"F\n" +
	"\n" +
	"TunnelInfo\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\rR\x03tag\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\vStdoutEvent\x12\x1f\n" +
	"\vprocess_tag\x18\x01 \x01(\rR\n" +
	"processTag\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"B\n" +
	"\vStderrEvent\x12\x1f\n" +
	"\vprocess_tag\x18\x01 \x01(\rR\n" +
	"processTag\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"I\n" +
	"\tExitEvent\x12\x1f\n" +
	"\vprocess_tag\x18\x01 \x01(\rR\n" +
	"processTag\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\"]\n" +
	"\rFsChangeEvent\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\rR\awatchId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventTypeB0Z.github.com/Lincyaw/agent-env/pkg/pb/executorv2b\x06proto3"

var (
	file_proto_executor_v2_proto_rawDescOnce sync.Once
	file_proto_executor_v2_proto_rawDescData []byte
)

func file_proto_executor_v2_proto_rawDescGZIP() []byte {
	file_proto_executor_v2_proto_rawDescOnce.Do(func() {
		file_proto_executor_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_executor_v2_proto_rawDesc), len(file_proto_executor_v2_proto_rawDesc)))
	})
	return file_proto_executor_v2_proto_rawDescData
}

var file_proto_executor_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_proto_executor_v2_proto_goTypes = []any{
	(*Request)(nil),             // 0: arl.executor.v2.Request
	(*Response)(nil),            // 1: arl.executor.v2.Response
	(*Event)(nil),               // 2: arl.executor.v2.Event
	(*PingRequest)(nil),         // 3: arl.executor.v2.PingRequest
	(*PingResponse)(nil),        // 4: arl.executor.v2.PingResponse
	(*SpawnRequest)(nil),        // 5: arl.executor.v2.SpawnRequest
	(*SpawnResponse)(nil),       // 6: arl.executor.v2.SpawnResponse
	(*WriteInRequest)(nil),      // 7: arl.executor.v2.WriteInRequest
	(*WriteInResponse)(nil),     // 8: arl.executor.v2.WriteInResponse
	(*SignalRequest)(nil),       // 9: arl.executor.v2.SignalRequest
	(*SignalResponse)(nil),      // 10: arl.executor.v2.SignalResponse
	(*ResizeRequest)(nil),       // 11: arl.executor.v2.ResizeRequest
	(*ResizeResponse)(nil),      // 12: arl.executor.v2.ResizeResponse
	(*ReadRequest)(nil),         // 13: arl.executor.v2.ReadRequest
	(*ReadResponse)(nil),        // 14: arl.executor.v2.ReadResponse
	(*WriteRequest)(nil),        // 15: arl.executor.v2.WriteRequest
	(*WriteResponse)(nil),       // 16: arl.executor.v2.WriteResponse
	(*StatRequest)(nil),         // 17: arl.executor.v2.StatRequest
	(*StatResponse)(nil),        // 18: arl.executor.v2.StatResponse
	(*ListRequest)(nil),         // 19: arl.executor.v2.ListRequest
	(*ListResponse)(nil),        // 20: arl.executor.v2.ListResponse
	(*DirEntry)(nil),            // 21: arl.executor.v2.DirEntry
	(*TunnelRequest)(nil),       // 22: arl.executor.v2.TunnelRequest
	(*TunnelResponse)(nil),      // 23: arl.executor.v2.TunnelResponse
	(*WatchRequest)(nil),        // 24: arl.executor.v2.WatchRequest
	(*WatchResponse)(nil),       // 25: arl.executor.v2.WatchResponse
	(*UnwatchRequest)(nil),      // 26: arl.executor.v2.UnwatchRequest
	(*UnwatchResponse)(nil),     // 27: arl.executor.v2.UnwatchResponse
	(*CloseTunnelRequest)(nil),  // 28: arl.executor.v2.CloseTunnelRequest
	(*CloseTunnelResponse)(nil), // 29: arl.executor.v2.CloseTunnelResponse
	(*ListTunnelsRequest)(nil),  // 30: arl.executor.v2.ListTunnelsRequest
	(*ListTunnelsResponse)(nil), // 31: arl.executor.v2.ListTunnelsResponse
	(*TunnelInfo)(nil),          // 32: arl.executor.v2.TunnelInfo
	(*ErrorResponse)(nil),       // 33: arl.executor.v2.ErrorResponse
	(*StdoutEvent)(nil),         // 34: arl.executor.v2.StdoutEvent
	(*StderrEvent)(nil),         // 35: arl.executor.v2.StderrEvent
	(*ExitEvent)(nil),           // 36: arl.executor.v2.ExitEvent
	(*FsChangeEvent)(nil),       // 37: arl.executor.v2.FsChangeEvent
	nil,                         // 38: arl.executor.v2.SpawnRequest.EnvEntry
}
var file_proto_executor_v2_proto_depIdxs = []int32{
	3,  // 0: arl.executor.v2.Request.ping:type_name -> arl.executor.v2.PingRequest
	5,  // 1: arl.executor.v2.Request.spawn:type_name -> arl.executor.v2.SpawnRequest
	7,  // 2: arl.executor.v2.Request.write_in:type_name -> arl.executor.v2.WriteInRequest
	9,  // 3: arl.executor.v2.Request.signal:type_name -> arl.executor.v2.SignalRequest
	11, // 4: arl.executor.v2.Request.resize:type_name -> arl.executor.v2.ResizeRequest
	13, // 5: arl.executor.v2.Request.read:type_name -> arl.executor.v2.ReadRequest
	15, // 6: arl.executor.v2.Request.write:type_name -> arl.executor.v2.WriteRequest
	17, // 7: arl.executor.v2.Request.stat:type_name -> arl.executor.v2.StatRequest
	19, // 8: arl.executor.v2.Request.list:type_name -> arl.executor.v2.ListRequest
	22, // 9: arl.executor.v2.Request.tunnel:type_name -> arl.executor.v2.TunnelRequest
	24, // 10: arl.executor.v2.Request.watch:type_name -> arl.executor.v2.WatchRequest
	26, // 11: arl.executor.v2.Request.unwatch:type_name -> arl.executor.v2.UnwatchRequest
	28, // 12: arl.executor.v2.Request.close_tunnel:type_name -> arl.executor.v2.CloseTunnelRequest
	30, // 13: arl.executor.v2.Request.list_tunnels:type_name -> arl.executor.v2.ListTunnelsRequest
	4,  // 14: arl.executor.v2.Response.ping:type_name -> arl.executor.v2.PingResponse
	6,  // 15: arl.executor.v2.Response.spawn:type_name -> arl.executor.v2.SpawnResponse
	8,  // 16: arl.executor.v2.Response.write_in:type_name -> arl.executor.v2.WriteInResponse
	10, // 17: arl.executor.v2.Response.signal:type_name -> arl.executor.v2.SignalResponse
	12, // 18: arl.executor.v2.Response.resize:type_name -> arl.executor.v2.ResizeResponse
	14, // 19: arl.executor.v2.Response.read:type_name -> arl.executor.v2.ReadResponse
	16, // 20: arl.executor.v2.Response.write:type_name -> arl.executor.v2.WriteResponse
	18, // 21: arl.executor.v2.Response.stat:type_name -> arl.executor.v2.StatResponse
	20, // 22: arl.executor.v2.Response.list:type_name -> arl.executor.v2.ListResponse
	23, // 23: arl.executor.v2.Response.tunnel:type_name -> arl.executor.v2.TunnelResponse
	25, // 24: arl.executor.v2.Response.watch:type_name -> arl.executor.v2.WatchResponse
	27, // 25: arl.executor.v2.Response.unwatch:type_name -> arl.executor.v2.UnwatchResponse
	33, // 26: arl.executor.v2.Response.error:type_name -> arl.executor.v2.ErrorResponse
	29, // 27: arl.executor.v2.Response.close_tunnel:type_name -> arl.executor.v2.CloseTunnelResponse
	31, // 28: arl.executor.v2.Response.list_tunnels:type_name -> arl.executor.v2.ListTunnelsResponse
	34, // 29: arl.executor.v2.Event.stdout:type_name -> arl.executor.v2.StdoutEvent
	35, // 30: arl.executor.v2.Event.stderr:type_name -> arl.executor.v2.StderrEvent
	36, // 31: arl.executor.v2.Event.exit:type_name -> arl.executor.v2.ExitEvent
	37, // 32: arl.executor.v2.Event.fs_change:type_name -> arl.executor.v2.FsChangeEvent
	38, // 33: arl.executor.v2.SpawnRequest.env:type_name -> arl.executor.v2.SpawnRequest.EnvEntry
	21, // 34: arl.executor.v2.ListResponse.entries:type_name -> arl.executor.v2.DirEntry
	32, // 35: arl.executor.v2.ListTunnelsResponse.tunnels:type_name -> arl.executor.v2.TunnelInfo
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_proto_executor_v2_proto_init() }
func file_proto_executor_v2_proto_init() {
	if File_proto_executor_v2_proto != nil {
		return
	}
	file_proto_executor_v2_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Ping)(nil),
		(*Request_Spawn)(nil),
		(*Request_WriteIn)(nil),
		(*Request_Signal)(nil),
		(*Request_Resize)(nil),
		(*Request_Read)(nil),
		(*Request_Write)(nil),
		(*Request_Stat)(nil),
		(*Request_List)(nil),
		(*Request_Tunnel)(nil),
		(*Request_Watch)(nil),
		(*Request_Unwatch)(nil),
		(*Request_CloseTunnel)(nil),
		(*Request_ListTunnels)(nil),
	}
	file_proto_executor_v2_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_Ping)(nil),
		(*Response_Spawn)(nil),
		(*Response_WriteIn)(nil),
		(*Response_Signal)(nil),
		(*Response_Resize)(nil),
		(*Response_Read)(nil),
		(*Response_Write)(nil),
		(*Response_Stat)(nil),
		(*Response_List)(nil),
		(*Response_Tunnel)(nil),
		(*Response_Watch)(nil),
		(*Response_Unwatch)(nil),
		(*Response_Error)(nil),
		(*Response_CloseTunnel)(nil),
		(*Response_ListTunnels)(nil),
	}
	file_proto_executor_v2_proto_msgTypes[2].OneofWrappers = []any{
		(*Event_Stdout)(nil),
		(*Event_Stderr)(nil),
		(*Event_Exit)(nil),
		(*Event_FsChange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_executor_v2_proto_rawDesc), len(file_proto_executor_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_executor_v2_proto_goTypes,
		DependencyIndexes: file_proto_executor_v2_proto_depIdxs,
		MessageInfos:      file_proto_executor_v2_proto_msgTypes,
	}.Build()
	File_proto_executor_v2_proto = out.File
	file_proto_executor_v2_proto_goTypes = nil
	file_proto_executor_v2_proto_depIdxs = nil
}
