// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecRequest specifies a command to execute
type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	Env            map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir     string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Background     bool                   `protobuf:"varint,4,opt,name=background,proto3" json:"background,omitempty"` // true for Service mode, false for Job mode
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecRequest) GetBackground() bool {
	if x != nil {
		return x.Background
	}
	return false
}

func (x *ExecRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// ExecLog streams output from command execution
type ExecLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecLog) Reset() {
	*x = ExecLog{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecLog) ProtoMessage() {}

func (x *ExecLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecLog.ProtoReflect.Descriptor instead.
func (*ExecLog) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecLog) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecLog) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecLog) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecLog) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

// WriteFileChunk streams raw bytes to a relative path inside the workspace.
// The first chunk must set path. expected_sha256 is optional.
type WriteFileChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data           []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ExpectedSha256 string                 `protobuf:"bytes,3,opt,name=expected_sha256,json=expectedSha256,proto3" json:"expected_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteFileChunk) Reset() {
	*x = WriteFileChunk{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileChunk) ProtoMessage() {}

func (x *WriteFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileChunk.ProtoReflect.Descriptor instead.
func (*WriteFileChunk) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *WriteFileChunk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteFileChunk) GetExpectedSha256() string {
	if x != nil {
		return x.ExpectedSha256
	}
	return ""
}

// WriteFileResponse reports how many bytes were written.
type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	BytesWritten  int64                  `protobuf:"varint,2,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *WriteFileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *WriteFileResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// ReadFileRequest reads raw bytes from a relative path inside the workspace.
type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// FileChunk streams raw bytes from a file. The final message sets done=true
// and carries size_bytes and sha256.
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Done          bool                   `protobuf:"varint,6,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *FileChunk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileChunk) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileChunk) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *FileChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

// ShellInput represents input to an interactive shell session
type ShellInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*ShellInput_Data
	//	*ShellInput_Signal
	Input         isShellInput_Input `protobuf_oneof:"input"`
	Resize        bool               `protobuf:"varint,3,opt,name=resize,proto3" json:"resize,omitempty"` // Terminal resize event
	Rows          int32              `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`     // Terminal rows (used with resize)
	Cols          int32              `protobuf:"varint,5,opt,name=cols,proto3" json:"cols,omitempty"`     // Terminal columns (used with resize)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellInput) Reset() {
	*x = ShellInput{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellInput) ProtoMessage() {}

func (x *ShellInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellInput.ProtoReflect.Descriptor instead.
func (*ShellInput) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ShellInput) GetInput() isShellInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ShellInput) GetData() string {
	if x != nil {
		if x, ok := x.Input.(*ShellInput_Data); ok {
			return x.Data
		}
	}
	return ""
}

func (x *ShellInput) GetSignal() string {
	if x != nil {
		if x, ok := x.Input.(*ShellInput_Signal); ok {
			return x.Signal
		}
	}
	return ""
}

func (x *ShellInput) GetResize() bool {
	if x != nil {
		return x.Resize
	}
	return false
}

func (x *ShellInput) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ShellInput) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type isShellInput_Input interface {
	isShellInput_Input()
}

type ShellInput_Data struct {
	Data string `protobuf:"bytes,1,opt,name=data,proto3,oneof"` // Stdin data to send to the shell
}

type ShellInput_Signal struct {
	Signal string `protobuf:"bytes,2,opt,name=signal,proto3,oneof"` // Signal to send (e.g., "SIGINT" for Ctrl+C)
}

func (*ShellInput_Data) isShellInput_Input() {}

func (*ShellInput_Signal) isShellInput_Input() {}

// ShellOutput represents output from an interactive shell session
type ShellOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                          // Stdout/stderr data from the shell
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // Exit code (set when shell exits)
	Closed        bool                   `protobuf:"varint,3,opt,name=closed,proto3" json:"closed,omitempty"`                     // True when shell session has ended
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellOutput) Reset() {
	*x = ShellOutput{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellOutput) ProtoMessage() {}

func (x *ShellOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellOutput.ProtoReflect.Descriptor instead.
func (*ShellOutput) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ShellOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ShellOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ShellOutput) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

// LogsRequest configures log streaming
type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Follow        bool                   `protobuf:"varint,1,opt,name=follow,proto3" json:"follow,omitempty"`                        // Follow new log lines (like tail -f)
	TailLines     int32                  `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"` // Number of recent lines to return (0 = all buffered)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

// LogEntry is a single log line
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // RFC3339Nano
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`         // info, warn, error
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`     // Log line content
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`       // "sidecar", "executor", "exec"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// StatRequest asks for file metadata at a given path.
type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// StatResponse returns file metadata.
type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`         // octal permission string, e.g. "0644"
	Modified      string                 `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"` // Unix timestamp as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *StatResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *StatResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StatResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StatResponse) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

// ListDirRequest asks for directory listing.
type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListDirRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

// ListDirResponse contains the directory entries.
type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntryProto       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ListDirResponse) GetEntries() []*DirEntryProto {
	if x != nil {
		return x.Entries
	}
	return nil
}

// DirEntryProto is a single directory entry.
type DirEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntryProto) Reset() {
	*x = DirEntryProto{}
	mi := &file_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntryProto) ProtoMessage() {}

func (x *DirEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntryProto.ProtoReflect.Descriptor instead.
func (*DirEntryProto) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *DirEntryProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntryProto) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *DirEntryProto) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// WriteStdinRequest sends data to the stdin of a running process.
type WriteStdinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteStdinRequest) Reset() {
	*x = WriteStdinRequest{}
	mi := &file_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteStdinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStdinRequest) ProtoMessage() {}

func (x *WriteStdinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStdinRequest.ProtoReflect.Descriptor instead.
func (*WriteStdinRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *WriteStdinRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *WriteStdinRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// WriteStdinResponse is returned after writing stdin data.
type WriteStdinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteStdinResponse) Reset() {
	*x = WriteStdinResponse{}
	mi := &file_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteStdinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStdinResponse) ProtoMessage() {}

func (x *WriteStdinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStdinResponse.ProtoReflect.Descriptor instead.
func (*WriteStdinResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{16}
}

// GetIrohAddrRequest is empty; no parameters needed.
type GetIrohAddrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIrohAddrRequest) Reset() {
	*x = GetIrohAddrRequest{}
	mi := &file_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIrohAddrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIrohAddrRequest) ProtoMessage() {}

func (x *GetIrohAddrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIrohAddrRequest.ProtoReflect.Descriptor instead.
func (*GetIrohAddrRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{17}
}

// GetIrohAddrResponse carries the JSON-serialized iroh NodeAddr.
type GetIrohAddrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddrJson      string                 `protobuf:"bytes,1,opt,name=addr_json,json=addrJson,proto3" json:"addr_json,omitempty"` // JSON-serialized iroh NodeAddr, empty if not available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIrohAddrResponse) Reset() {
	*x = GetIrohAddrResponse{}
	mi := &file_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIrohAddrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIrohAddrResponse) ProtoMessage() {}

func (x *GetIrohAddrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIrohAddrResponse.ProtoReflect.Descriptor instead.
func (*GetIrohAddrResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *GetIrohAddrResponse) GetAddrJson() string {
	if x != nil {
		return x.AddrJson
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\varl.sidecar\"\xfe\x01\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x123\n" +
	"\x03env\x18\x02 \x03(\v2!.arl.sidecar.ExecRequest.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12\x1e\n" +
	"\n" +
	"background\x18\x04 \x01(\bR\n" +
	"background\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\aExecLog\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\fR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\"a\n" +
	"\x0eWriteFileChunk\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12'\n" +
	"\x0fexpected_sha256\x18\x03 \x01(\tR\x0eexpectedSha256\"d\n" +
	"\x11WriteFileResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\rbytes_written\x18\x02 \x01(\x03R\fbytesWritten\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x96\x01\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04done\x18\x06 \x01(\bR\x04done\"\x85\x01\n" +
	"\n" +
	"ShellInput\x12\x14\n" +
	"\x04data\x18\x01 \x01(\tH\x00R\x04data\x12\x18\n" +
	"\x06signal\x18\x02 \x01(\tH\x00R\x06signal\x12\x16\n" +
	"\x06resize\x18\x03 \x01(\bR\x06resize\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\x05 \x01(\x05R\x04colsB\a\n" +
	"\x05input\"V\n" +
	"\vShellOutput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06closed\x18\x03 \x01(\bR\x06closed\"D\n" +
	"\vLogsRequest\x12\x16\n" +
	"\x06follow\x18\x01 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\x05R\ttailLines\"p\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x81\x01\n" +
	"\fStatResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x1a\n" +
	"\bmodified\x18\x05 \x01(\tR\bmodified\"B\n" +
	"\x0eListDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"G\n" +
	"\x0fListDirResponse\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.arl.sidecar.DirEntryProtoR\aentries\"N\n" +
	"\rDirEntryProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"?\n" +
	"\x11WriteStdinRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x14\n" +
	"\x12WriteStdinResponse\"\x14\n" +
	"\x12GetIrohAddrRequest\"2\n" +
	"\x13GetIrohAddrResponse\x12\x1b\n" +
	"\taddr_json\x18\x01 \x01(\tR\baddrJson2\x8b\x05\n" +
	"\fAgentService\x12;\n" +
	"\aExecute\x12\x18.arl.sidecar.ExecRequest\x1a\x14.arl.sidecar.ExecLog0\x01\x12J\n" +
	"\tWriteFile\x12\x1b.arl.sidecar.WriteFileChunk\x1a\x1e.arl.sidecar.WriteFileResponse(\x01\x12B\n" +
	"\bReadFile\x12\x1c.arl.sidecar.ReadFileRequest\x1a\x16.arl.sidecar.FileChunk0\x01\x12;\n" +
	"\x04Stat\x12\x18.arl.sidecar.StatRequest\x1a\x19.arl.sidecar.StatResponse\x12D\n" +
	"\aListDir\x12\x1b.arl.sidecar.ListDirRequest\x1a\x1c.arl.sidecar.ListDirResponse\x12M\n" +
	"\n" +
	"WriteStdin\x12\x1e.arl.sidecar.WriteStdinRequest\x1a\x1f.arl.sidecar.WriteStdinResponse\x12I\n" +
	"\x10InteractiveShell\x12\x17.arl.sidecar.ShellInput\x1a\x18.arl.sidecar.ShellOutput(\x010\x01\x12?\n" +
	"\n" +
	"StreamLogs\x12\x18.arl.sidecar.LogsRequest\x1a\x15.arl.sidecar.LogEntry0\x01\x12P\n" +
	"\vGetIrohAddr\x12\x1f.arl.sidecar.GetIrohAddrRequest\x1a .arl.sidecar.GetIrohAddrResponseB%Z#github.com/Lincyaw/agent-env/pkg/pbb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_agent_proto_goTypes = []any{
	(*ExecRequest)(nil),         // 0: arl.sidecar.ExecRequest
	(*ExecLog)(nil),             // 1: arl.sidecar.ExecLog
	(*WriteFileChunk)(nil),      // 2: arl.sidecar.WriteFileChunk
	(*WriteFileResponse)(nil),   // 3: arl.sidecar.WriteFileResponse
	(*ReadFileRequest)(nil),     // 4: arl.sidecar.ReadFileRequest
	(*FileChunk)(nil),           // 5: arl.sidecar.FileChunk
	(*ShellInput)(nil),          // 6: arl.sidecar.ShellInput
	(*ShellOutput)(nil),         // 7: arl.sidecar.ShellOutput
	(*LogsRequest)(nil),         // 8: arl.sidecar.LogsRequest
	(*LogEntry)(nil),            // 9: arl.sidecar.LogEntry
	(*StatRequest)(nil),         // 10: arl.sidecar.StatRequest
	(*StatResponse)(nil),        // 11: arl.sidecar.StatResponse
	(*ListDirRequest)(nil),      // 12: arl.sidecar.ListDirRequest
	(*ListDirResponse)(nil),     // 13: arl.sidecar.ListDirResponse
	(*DirEntryProto)(nil),       // 14: arl.sidecar.DirEntryProto
	(*WriteStdinRequest)(nil),   // 15: arl.sidecar.WriteStdinRequest
	(*WriteStdinResponse)(nil),  // 16: arl.sidecar.WriteStdinResponse
	(*GetIrohAddrRequest)(nil),  // 17: arl.sidecar.GetIrohAddrRequest
	(*GetIrohAddrResponse)(nil), // 18: arl.sidecar.GetIrohAddrResponse
	nil,                         // 19: arl.sidecar.ExecRequest.EnvEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	19, // 0: arl.sidecar.ExecRequest.env:type_name -> arl.sidecar.ExecRequest.EnvEntry
	14, // 1: arl.sidecar.ListDirResponse.entries:type_name -> arl.sidecar.DirEntryProto
	0,  // 2: arl.sidecar.AgentService.Execute:input_type -> arl.sidecar.ExecRequest
	2,  // 3: arl.sidecar.AgentService.WriteFile:input_type -> arl.sidecar.WriteFileChunk
	4,  // 4: arl.sidecar.AgentService.ReadFile:input_type -> arl.sidecar.ReadFileRequest
	10, // 5: arl.sidecar.AgentService.Stat:input_type -> arl.sidecar.StatRequest
	12, // 6: arl.sidecar.AgentService.ListDir:input_type -> arl.sidecar.ListDirRequest
	15, // 7: arl.sidecar.AgentService.WriteStdin:input_type -> arl.sidecar.WriteStdinRequest
	6,  // 8: arl.sidecar.AgentService.InteractiveShell:input_type -> arl.sidecar.ShellInput
	8,  // 9: arl.sidecar.AgentService.StreamLogs:input_type -> arl.sidecar.LogsRequest
	17, // 10: arl.sidecar.AgentService.GetIrohAddr:input_type -> arl.sidecar.GetIrohAddrRequest
	1,  // 11: arl.sidecar.AgentService.Execute:output_type -> arl.sidecar.ExecLog
	3,  // 12: arl.sidecar.AgentService.WriteFile:output_type -> arl.sidecar.WriteFileResponse
	5,  // 13: arl.sidecar.AgentService.ReadFile:output_type -> arl.sidecar.FileChunk
	11, // 14: arl.sidecar.AgentService.Stat:output_type -> arl.sidecar.StatResponse
	13, // 15: arl.sidecar.AgentService.ListDir:output_type -> arl.sidecar.ListDirResponse
	16, // 16: arl.sidecar.AgentService.WriteStdin:output_type -> arl.sidecar.WriteStdinResponse
	7,  // 17: arl.sidecar.AgentService.InteractiveShell:output_type -> arl.sidecar.ShellOutput
	9,  // 18: arl.sidecar.AgentService.StreamLogs:output_type -> arl.sidecar.LogEntry
	18, // 19: arl.sidecar.AgentService.GetIrohAddr:output_type -> arl.sidecar.GetIrohAddrResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	file_proto_agent_proto_msgTypes[6].OneofWrappers = []any{
		(*ShellInput_Data)(nil),
		(*ShellInput_Signal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
